#!/usr/bin/env python3
"""
gen_layouts.py - build-time step: shaders/halo_shaders.json (Stage 2b/3 output)
-> shaders/xv_layouts.h, the C tables the runtime uses to create GXM vertex
programs for each recompiled Xbox vertex shader.

For every shader: the .gxp path inside the VPK, stream strides, one attribute
record per declared v-register (GXM format + component count derived from the
D3DVSDT type), extra records for constant-fed registers (bound to the instance
indexed constant stream, see xv_shader.c), the c[] uniform window (C_BASE, count)
read back from the generated .cg header, and - when the XBE is given - the FNV-1a
hash of the original function blob so the D3D HLE can recognise it when the
recompiled game calls CreateVertexShader() with a pointer into guest memory.

Usage: gen_layouts.py shaders/halo_shaders.json shaders/xv_layouts.h [GAME.xbe manifest.json]
"""

from __future__ import annotations

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import shader_recomp_gen as s3  # noqa: E402  (VREG_INPUT: v-register -> AppIn member name)

TYPE_FMT = {
    "FLOAT1": ("SCE_GXM_ATTRIBUTE_FORMAT_F32", 1), "FLOAT2": ("SCE_GXM_ATTRIBUTE_FORMAT_F32", 2),
    "FLOAT3": ("SCE_GXM_ATTRIBUTE_FORMAT_F32", 3), "FLOAT4": ("SCE_GXM_ATTRIBUTE_FORMAT_F32", 4),
    "D3DCOLOR": ("SCE_GXM_ATTRIBUTE_FORMAT_U8N", 4),
    "SHORT2": ("SCE_GXM_ATTRIBUTE_FORMAT_S16", 2), "SHORT4": ("SCE_GXM_ATTRIBUTE_FORMAT_S16", 4),
    "NORMSHORT1": ("SCE_GXM_ATTRIBUTE_FORMAT_S16N", 1), "NORMSHORT2": ("SCE_GXM_ATTRIBUTE_FORMAT_S16N", 2),
    "NORMSHORT3": ("SCE_GXM_ATTRIBUTE_FORMAT_S16N", 3), "NORMSHORT4": ("SCE_GXM_ATTRIBUTE_FORMAT_S16N", 4),
    "NORMPACKED3": ("SCE_GXM_ATTRIBUTE_FORMAT_U8", 4),
    "FLOAT2H": ("SCE_GXM_ATTRIBUTE_FORMAT_F32", 3),
    "PBYTE1": ("SCE_GXM_ATTRIBUTE_FORMAT_U8N", 1), "PBYTE2": ("SCE_GXM_ATTRIBUTE_FORMAT_U8N", 2),
    "PBYTE3": ("SCE_GXM_ATTRIBUTE_FORMAT_U8N", 3), "PBYTE4": ("SCE_GXM_ATTRIBUTE_FORMAT_U8N", 4),
}
GENERIC_FMT = {"UB_D3D": "SCE_GXM_ATTRIBUTE_FORMAT_U8N", "S1": "SCE_GXM_ATTRIBUTE_FORMAT_S16N",
               "F": "SCE_GXM_ATTRIBUTE_FORMAT_F32", "UB_OGL": "SCE_GXM_ATTRIBUTE_FORMAT_U8N",
               "S32K": "SCE_GXM_ATTRIBUTE_FORMAT_S16", "CMP": "SCE_GXM_ATTRIBUTE_FORMAT_U8"}


def fmt_of(tname: str):
    if tname in TYPE_FMT:
        return TYPE_FMT[tname]
    m = re.match(r"^([A-Z_0-9]+?)x(\d)$", tname)
    if m and m.group(1) in GENERIC_FMT:
        return GENERIC_FMT[m.group(1)], (4 if m.group(1) == "CMP" else int(m.group(2)))
    raise SystemExit(f"unknown attribute type {tname}")


def c_window(cg_path: str):
    try:
        head = open(cg_path, "r", encoding="utf-8").read(2048)
        m = re.search(r"uniform float4 c\[(\d+)\]\s+-\s+universal constant array, C_BASE = (-?\d+)", head)
        if m:
            return int(m.group(2)), int(m.group(1))
    except OSError:
        pass
    return 0, 96


def fnv1a(data: bytes) -> int:
    h = 0x811C9DC5
    for b in data:
        h = ((h ^ b) * 0x01000193) & 0xFFFFFFFF
    return h


class BlobReader:
    """Reads Xbox function blobs out of the XBE using the Stage 1 manifest."""

    def __init__(self, xbe: str, manifest: str):
        self.data = open(xbe, "rb").read()
        m = json.load(open(manifest, "r", encoding="utf-8"))
        self.secs = [(s["virtual_address"], s["raw_address"], s["raw_size"]) for s in m["sections"]]

    def blob(self, va: int):
        for sva, roff, rsize in self.secs:
            if sva <= va < sva + rsize:
                off = roff + (va - sva)
                n = self.data[off + 2]
                size = 4 + 16 * n
                return self.data[off:off + size]
        raise SystemExit(f"function VA 0x{va:08X} not in any section")


def attr_line(member, stream, offset, fmt, n, vreg, comment):
    return f'    {{ "{member}", {stream}, {offset}, {fmt}, {n}, {vreg} }},  /* {comment} */'


def manual_desc(out, name, gxp, stride, attrs, c_base, c_count, decl_va=0):
    out.append(f"static const xv_attr_desc_t xv_attrs_{name}[] = {{")
    out += attrs
    out.append("};")
    out.append(f"static const xv_vs_desc_t xv_vs_{name} = {{")
    out.append(f'    "app0:shaders/{gxp}", 1, {{ {stride}, 0, 0, 0 }}, {len(attrs)}, xv_attrs_{name}, '
               f"{c_base}, {c_count}, 0u, 0x{decl_va:08X}u, 0u, 0u")
    out.append("};")
    out.append("")


def main() -> int:
    if len(sys.argv) not in (3, 5):
        print(__doc__)
        return 2
    src, dst = sys.argv[1], sys.argv[2]
    reader = BlobReader(sys.argv[3], sys.argv[4]) if len(sys.argv) == 5 else None
    shaders = json.load(open(src, "r", encoding="utf-8"))

    out = [f"/* Generated by gen_layouts.py from {os.path.basename(src)} - do not edit. */",
           "#pragma once", '#include "xv_shader.h"', ""]
    names = []
    for sh in shaders:
        base = os.path.splitext(os.path.basename(sh["cg"]))[0]
        names.append(base)
        attrs = []
        for a in sh["attributes"]:
            fmt, n = fmt_of(a["type"])
            attrs.append(attr_line(s3.VREG_INPUT[int(a["vreg"])][0], a["stream"], a["offset"], fmt, n,
                                   a["vreg"], f'v{a["vreg"]} {a["type"]}'))
        for v in sh.get("constant_fed_inputs", []):
            vreg = int(v[1:])
            attrs.append(attr_line(s3.VREG_INPUT[vreg][0], "XV_CONST_STREAM", 0, "SCE_GXM_ATTRIBUTE_FORMAT_F32", 4,
                                   vreg, f"v{vreg} constant-fed (SetVertexData4f)"))
        out.append(f"static const xv_attr_desc_t xv_attrs_{base}[] = {{")
        out += attrs if attrs else ["    { 0 }"]
        out.append("};")
        strides = [0, 0, 0, 0]
        for k, v in sh["streams"].items():
            strides[int(k)] = int(v)
        nstreams = max([int(k) for k in sh["streams"]] + [-1]) + 1
        c_base, c_count = c_window(sh["cg"])
        fh, fs = 0, 0
        if reader:
            blob = reader.blob(int(sh["func_va"], 16))
            fh, fs = fnv1a(blob), len(blob)
        out.append(f"static const xv_vs_desc_t xv_vs_{base} = {{")
        out.append(f'    "app0:shaders/{base}.gxp", {nstreams}, {{ {strides[0]}, {strides[1]}, {strides[2]}, {strides[3]} }},')
        out.append(f"    {len(attrs)}, xv_attrs_{base}, {c_base}, {c_count}, {sh['func_va']}u, {sh['decl_va']}u, "
                   f"0x{fh:08X}u, {fs}u")
        out.append("};")
        out.append("")

    out.append(f"#define XV_HALO_VS_COUNT {len(shaders)}")
    out.append("static const xv_vs_desc_t *const xv_halo_vs[XV_HALO_VS_COUNT] = {")
    out += [f"    &xv_vs_{n}," for n in names]
    out.append("};")
    out.append("")

    # Runtime-owned shaders (hand-written Cg in shaders/, no Xbox blob):
    manual_desc(out, "ff_test", "halo_shader_0.gxp", 16, [
        attr_line("position", 0, 0, "SCE_GXM_ATTRIBUTE_FORMAT_F32", 3, 0, "v0 FLOAT3"),
        attr_line("texcoord0", 0, 12, "SCE_GXM_ATTRIBUTE_FORMAT_U8N", 4, 9, "v9 D3DCOLOR"),
    ], 0, 9, 0x1E1388)
    manual_desc(out, "clear", "xv_clear.gxp", 16, [
        attr_line("position", 0, 0, "SCE_GXM_ATTRIBUTE_FORMAT_F32", 3, 0, "clip-space xyz"),
        attr_line("color0", 0, 12, "SCE_GXM_ATTRIBUTE_FORMAT_U8N", 4, 3, "D3DCOLOR"),
    ], 0, 0)
    # Scene-viewer shader for Halo's compressed model vertex (declaration 0x1E1400).
    manual_desc(out, "model", "xv_model.gxp", 32, [
        attr_line("position", 0, 0, "SCE_GXM_ATTRIBUTE_FORMAT_F32", 3, 0, "v0 FLOAT3"),
        attr_line("blendweight", 0, 12, "SCE_GXM_ATTRIBUTE_FORMAT_U8", 4, 1, "v1 NORMPACKED3 normal"),
        attr_line("normal", 0, 16, "SCE_GXM_ATTRIBUTE_FORMAT_U8", 4, 2, "v2 NORMPACKED3 binormal"),
        attr_line("color0", 0, 20, "SCE_GXM_ATTRIBUTE_FORMAT_U8", 4, 3, "v3 NORMPACKED3 tangent"),
        attr_line("color1", 0, 24, "SCE_GXM_ATTRIBUTE_FORMAT_S16N", 2, 4, "v4 NORMSHORT2 texcoord"),
        attr_line("fog", 0, 28, "SCE_GXM_ATTRIBUTE_FORMAT_U8N", 2, 5, "v5 PBYTE2 node indices"),
        attr_line("psize", 0, 30, "SCE_GXM_ATTRIBUTE_FORMAT_S16N", 1, 6, "v6 NORMSHORT1 node weight"),
    ], 0, 6, 0x1E1400)
    manual_desc(out, "test_tex", "xv_test_tex.gxp", 24, [
        attr_line("position", 0, 0, "SCE_GXM_ATTRIBUTE_FORMAT_F32", 3, 0, "v0 FLOAT3"),
        attr_line("texcoord0", 0, 12, "SCE_GXM_ATTRIBUTE_FORMAT_F32", 2, 9, "v9 FLOAT2"),
        attr_line("color0", 0, 20, "SCE_GXM_ATTRIBUTE_FORMAT_U8N", 4, 3, "v3 D3DCOLOR"),
    ], 0, 4)

    with open(dst, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {dst}: {len(shaders)} Halo layouts{' (with blob hashes)' if reader else ''} + 3 runtime shaders")
    return 0


if __name__ == "__main__":
    sys.exit(main())
