"""Xbox kernel (xboxkrnl.exe) export ordinals -> names.  Shared by the recompiler
(kernel thunk resolution) and the kernel translator generator."""

KERNEL_EXPORTS = {
    1: "AvGetSavedDataAddress", 2: "AvSendTVEncoderOption", 3: "AvSetDisplayMode", 4: "AvSetSavedDataAddress",
    5: "DbgBreakPoint", 6: "DbgBreakPointWithStatus", 7: "DbgLoadImageSymbols", 8: "DbgPrint",
    9: "HalReadSMCTrayState", 10: "DbgPrompt", 11: "DbgUnLoadImageSymbols", 12: "ExAcquireReadWriteLockExclusive",
    13: "ExAcquireReadWriteLockShared", 14: "ExAllocatePool", 15: "ExAllocatePoolWithTag", 16: "ExEventObjectType",
    17: "ExFreePool", 18: "ExInitializeReadWriteLock", 19: "ExInterlockedAddLargeInteger",
    20: "ExInterlockedAddLargeStatistic", 21: "ExInterlockedCompareExchange64", 22: "ExMutantObjectType",
    23: "ExQueryPoolBlockSize", 24: "ExQueryNonVolatileSetting", 25: "ExReadWriteRefurbInfo", 26: "ExRaiseException",
    27: "ExRaiseStatus", 28: "ExReleaseReadWriteLock", 29: "ExSaveNonVolatileSetting", 30: "ExSemaphoreObjectType",
    31: "ExTimerObjectType", 32: "ExfInterlockedInsertHeadList", 33: "ExfInterlockedInsertTailList",
    34: "ExfInterlockedRemoveHeadList", 35: "FscGetCacheSize", 36: "FscInvalidateIdleBlocks", 37: "FscSetCacheSize",
    38: "HalClearSoftwareInterrupt", 39: "HalDisableSystemInterrupt", 40: "HalDiskCachePartitionCount",
    41: "HalDiskModelNumber", 42: "HalDiskSerialNumber", 43: "HalEnableSystemInterrupt", 44: "HalGetInterruptVector",
    45: "HalReadSMBusValue", 46: "HalReadWritePCISpace", 47: "HalRegisterShutdownNotification",
    48: "HalRequestSoftwareInterrupt", 49: "HalReturnToFirmware", 50: "HalWriteSMBusValue",
    51: "InterlockedCompareExchange", 52: "InterlockedDecrement", 53: "InterlockedIncrement", 54: "InterlockedExchange",
    55: "InterlockedExchangeAdd", 56: "InterlockedFlushSList", 57: "InterlockedPopEntrySList",
    58: "InterlockedPushEntrySList", 59: "IoAllocateIrp", 60: "IoBuildAsynchronousFsdRequest",
    61: "IoBuildDeviceIoControlRequest", 62: "IoBuildSynchronousFsdRequest", 63: "IoCheckShareAccess",
    64: "IoCompletionObjectType", 65: "IoCreateDevice", 66: "IoCreateFile", 67: "IoCreateSymbolicLink",
    68: "IoDeleteDevice", 69: "IoDeleteSymbolicLink", 70: "IoDeviceObjectType", 71: "IoDismountVolume",
    72: "IoDismountVolumeByName", 73: "IoFileObjectType", 74: "IoFreeIrp", 75: "IoInitializeIrp",
    76: "IoInvalidDeviceRequest", 77: "IoQueryFileInformation", 78: "IoQueryVolumeInformation", 79: "IoQueueThreadIrp",
    80: "IoRemoveShareAccess", 81: "IoSetIoCompletion", 82: "IoSetShareAccess", 83: "IoStartNextPacket",
    84: "IoStartNextPacketByKey", 85: "IoStartPacket", 86: "IoSynchronousDeviceIoControlRequest",
    87: "IoSynchronousFsdRequest", 88: "IofCallDriver", 89: "IofCompleteRequest", 90: "KdDebuggerEnabled",
    91: "KdDebuggerNotPresent", 92: "KeAlertResumeThread", 93: "KeAlertThread", 94: "KeBoostPriorityThread",
    95: "KeBugCheck", 96: "KeBugCheckEx", 97: "KeCancelTimer", 98: "KeConnectInterrupt", 99: "KeDelayExecutionThread",
    100: "KeDisconnectInterrupt", 101: "KeEnterCriticalRegion", 102: "MmGlobalData", 103: "KeGetCurrentIrql",
    104: "KeGetCurrentThread", 105: "KeInitializeApc", 106: "KeInitializeDeviceQueue", 107: "KeInitializeDpc",
    108: "KeInitializeEvent", 109: "KeInitializeInterrupt", 110: "KeInitializeMutant", 111: "KeInitializeQueue",
    112: "KeInitializeSemaphore", 113: "KeInitializeTimerEx", 114: "KeInsertByKeyDeviceQueue",
    115: "KeInsertDeviceQueue", 116: "KeInsertHeadQueue", 117: "KeInsertQueue", 118: "KeInsertQueueApc",
    119: "KeInsertQueueDpc", 120: "KeInterruptTime", 121: "KeIsExecutingDpc", 122: "KeLeaveCriticalRegion",
    123: "KePulseEvent", 124: "KeQueryBasePriorityThread", 125: "KeQueryInterruptTime",
    126: "KeQueryPerformanceCounter", 127: "KeQueryPerformanceFrequency", 128: "KeQuerySystemTime",
    129: "KeRaiseIrqlToDpcLevel", 130: "KeRaiseIrqlToSynchLevel", 131: "KeReleaseMutant", 132: "KeReleaseSemaphore",
    133: "KeRemoveByKeyDeviceQueue", 134: "KeRemoveDeviceQueue", 135: "KeRemoveEntryDeviceQueue", 136: "KeRemoveQueue",
    137: "KeRemoveQueueDpc", 138: "KeResetEvent", 139: "KeRestoreFloatingPointState", 140: "KeResumeThread",
    141: "KeRundownQueue", 142: "KeSaveFloatingPointState", 143: "KeSetBasePriorityThread",
    144: "KeSetDisableBoostThread", 145: "KeSetEvent", 146: "KeSetEventBoostPriority", 147: "KeSetPriorityProcess",
    148: "KeSetPriorityThread", 149: "KeSetTimer", 150: "KeSetTimerEx", 151: "KeStallExecutionProcessor",
    152: "KeSuspendThread", 153: "KeSynchronizeExecution", 154: "KeSystemTime", 155: "KeTestAlertThread",
    156: "KeTickCount", 157: "KeTimeIncrement", 158: "KeWaitForMultipleObjects", 159: "KeWaitForSingleObject",
    160: "KfRaiseIrql", 161: "KfLowerIrql", 162: "KiBugCheckData", 163: "KiUnlockDispatcherDatabase",
    164: "LaunchDataPage", 165: "MmAllocateContiguousMemory", 166: "MmAllocateContiguousMemoryEx",
    167: "MmAllocateSystemMemory", 168: "MmClaimGpuInstanceMemory", 169: "MmCreateKernelStack",
    170: "MmDeleteKernelStack", 171: "MmFreeContiguousMemory", 172: "MmFreeSystemMemory", 173: "MmGetPhysicalAddress",
    174: "MmIsAddressValid", 175: "MmLockUnlockBufferPages", 176: "MmLockUnlockPhysicalPage", 177: "MmMapIoSpace",
    178: "MmPersistContiguousMemory", 179: "MmQueryAddressProtect", 180: "MmQueryAllocationSize",
    181: "MmQueryStatistics", 182: "MmSetAddressProtect", 183: "MmUnmapIoSpace", 184: "NtAllocateVirtualMemory",
    185: "NtCancelTimer", 186: "NtClearEvent", 187: "NtClose", 188: "NtCreateDirectoryObject", 189: "NtCreateEvent",
    190: "NtCreateFile", 191: "NtCreateIoCompletion", 192: "NtCreateMutant", 193: "NtCreateSemaphore",
    194: "NtCreateTimer", 195: "NtDeleteFile", 196: "NtDeviceIoControlFile", 197: "NtDuplicateObject",
    198: "NtFlushBuffersFile", 199: "NtFreeVirtualMemory", 200: "NtFsControlFile", 201: "NtOpenDirectoryObject",
    202: "NtOpenFile", 203: "NtOpenSymbolicLinkObject", 204: "NtProtectVirtualMemory", 205: "NtPulseEvent",
    206: "NtQueueApcThread", 207: "NtQueryDirectoryFile", 208: "NtQueryDirectoryObject", 209: "NtQueryEvent",
    210: "NtQueryFullAttributesFile", 211: "NtQueryInformationFile", 212: "NtQueryIoCompletion", 213: "NtQueryMutant",
    214: "NtQuerySemaphore", 215: "NtQuerySymbolicLinkObject", 216: "NtQueryTimer", 217: "NtQueryVirtualMemory",
    218: "NtQueryVolumeInformationFile", 219: "NtReadFile", 220: "NtReadFileScatter", 221: "NtReleaseMutant",
    222: "NtReleaseSemaphore", 223: "NtRemoveIoCompletion", 224: "NtResumeThread", 225: "NtSetEvent",
    226: "NtSetInformationFile", 227: "NtSetIoCompletion", 228: "NtSetSystemTime", 229: "NtSetTimerEx",
    230: "NtSignalAndWaitForSingleObjectEx", 231: "NtSuspendThread", 232: "NtUserIoApcDispatcher",
    233: "NtWaitForSingleObject", 234: "NtWaitForSingleObjectEx", 235: "NtWaitForMultipleObjectsEx", 236: "NtWriteFile",
    237: "NtWriteFileGather", 238: "NtYieldExecution", 239: "ObCreateObject", 240: "ObDirectoryObjectType",
    241: "ObInsertObject", 242: "ObMakeTemporaryObject", 243: "ObOpenObjectByName", 244: "ObOpenObjectByPointer",
    245: "ObpObjectHandleTable", 246: "ObReferenceObjectByHandle", 247: "ObReferenceObjectByName",
    248: "ObReferenceObjectByPointer", 249: "ObSymbolicLinkObjectType", 250: "ObfDereferenceObject",
    251: "ObfReferenceObject", 252: "PhyGetLinkState", 253: "PhyInitialize", 254: "PsCreateSystemThread",
    255: "PsCreateSystemThreadEx", 256: "PsQueryStatistics", 257: "PsSetCreateThreadNotifyRoutine",
    258: "PsTerminateSystemThread", 259: "PsThreadObjectType", 260: "RtlAnsiStringToUnicodeString",
    261: "RtlAppendStringToString", 262: "RtlAppendUnicodeStringToString", 263: "RtlAppendUnicodeToString",
    264: "RtlAssert", 265: "RtlCaptureContext", 266: "RtlCaptureStackBackTrace", 267: "RtlCharToInteger",
    268: "RtlCompareMemory", 269: "RtlCompareMemoryUlong", 270: "RtlCompareString", 271: "RtlCompareUnicodeString",
    272: "RtlCopyString", 273: "RtlCopyUnicodeString", 274: "RtlCreateUnicodeString", 275: "RtlDowncaseUnicodeChar",
    276: "RtlDowncaseUnicodeString", 277: "RtlEnterCriticalSection", 278: "RtlEnterCriticalSectionAndRegion",
    279: "RtlEqualString", 280: "RtlEqualUnicodeString", 281: "RtlExtendedIntegerMultiply",
    282: "RtlExtendedLargeIntegerDivide", 283: "RtlExtendedMagicDivide", 284: "RtlFillMemory", 285: "RtlFillMemoryUlong",
    286: "RtlFreeAnsiString", 287: "RtlFreeUnicodeString", 288: "RtlGetCallersAddress", 289: "RtlInitAnsiString",
    290: "RtlInitUnicodeString", 291: "RtlInitializeCriticalSection", 292: "RtlIntegerToChar",
    293: "RtlIntegerToUnicodeString", 294: "RtlLeaveCriticalSection", 295: "RtlLeaveCriticalSectionAndRegion",
    296: "RtlLowerChar", 297: "RtlMapGenericMask", 298: "RtlMoveMemory", 299: "RtlMultiByteToUnicodeN",
    300: "RtlMultiByteToUnicodeSize", 301: "RtlNtStatusToDosError", 302: "RtlRaiseException", 303: "RtlRaiseStatus",
    304: "RtlTimeFieldsToTime", 305: "RtlTimeToTimeFields", 306: "RtlTryEnterCriticalSection", 307: "RtlUlongByteSwap",
    308: "RtlUnicodeStringToAnsiString", 309: "RtlUnicodeStringToInteger", 310: "RtlUnicodeToMultiByteN",
    311: "RtlUnicodeToMultiByteSize", 312: "RtlUnwind", 313: "RtlUpcaseUnicodeChar", 314: "RtlUpcaseUnicodeString",
    315: "RtlUpcaseUnicodeToMultiByteN", 316: "RtlUpperChar", 317: "RtlUpperString", 318: "RtlUshortByteSwap",
    319: "RtlWalkFrameChain", 320: "RtlZeroMemory", 321: "XboxEEPROMKey", 322: "XboxHardwareInfo", 323: "XboxHDKey",
    324: "XboxKrnlVersion", 325: "XboxSignatureKey", 326: "XeImageFileName", 327: "XeLoadSection", 328: "XeUnloadSection",
    329: "READ_PORT_BUFFER_UCHAR", 330: "READ_PORT_BUFFER_USHORT", 331: "READ_PORT_BUFFER_ULONG",
    332: "WRITE_PORT_BUFFER_UCHAR", 333: "WRITE_PORT_BUFFER_USHORT", 334: "WRITE_PORT_BUFFER_ULONG", 335: "XcSHAInit",
    336: "XcSHAUpdate", 337: "XcSHAFinal", 338: "XcRC4Key", 339: "XcRC4Crypt", 340: "XcHMAC", 341: "XcPKEncPublic",
    342: "XcPKDecPrivate", 343: "XcPKGetKeyLen", 344: "XcVerifyPKCS1Signature", 345: "XcModExp", 346: "XcDESKeyParity",
    347: "XcKeyTable", 348: "XcBlockCrypt", 349: "XcBlockCryptCBC", 350: "XcCryptService", 351: "XcUpdateCrypto",
    352: "RtlRip", 353: "XboxLANKey", 354: "XboxAlternateSignatureKeys", 355: "XePublicKeyData",
    356: "HalBootSMCVideoMode", 357: "IdexChannelObject", 358: "HalIsResetOrShutdownPending", 359: "IoMarkIrpMustComplete",
    360: "HalInitiateShutdown", 361: "RtlSnprintf", 362: "RtlSprintf", 363: "RtlVsnprintf", 364: "RtlVsprintf",
    365: "HalEnableSecureTrayEject", 366: "HalWriteSMCScratchRegister",
}

# Exports that are DATA (variables), not functions: the thunk slot holds their address.
KERNEL_DATA_EXPORTS = {16, 22, 30, 31, 40, 41, 42, 64, 70, 73, 90, 91, 102, 120, 154, 156, 157, 162, 164, 240, 245,
                       249, 259, 321, 322, 323, 324, 325, 326, 353, 354, 355, 356, 357}

# Stack argument counts (stdcall) for the kernel exports the recompiler needs to stub.
# fastcall exports (KfRaiseIrql, KfLowerIrql, ExfInterlocked*, Interlocked*, IofCallDriver,
# IofCompleteRequest, ObfReferenceObject, ObfDereferenceObject) take register args -> 0.
KERNEL_ARGC = {
    "ExAllocatePool": 1, "ExAllocatePoolWithTag": 2, "ExFreePool": 1, "ExQueryPoolBlockSize": 1,
    "HalGetInterruptVector": 2, "HalInitiateShutdown": 0, "HalRegisterShutdownNotification": 2, "HalReturnToFirmware": 1,
    "IoCreateSymbolicLink": 2, "KeBugCheck": 1, "KeCancelTimer": 1, "KeConnectInterrupt": 1, "KeDelayExecutionThread": 3,
    "KeDisconnectInterrupt": 1, "KeInitializeDpc": 3, "KeInitializeInterrupt": 7, "KeInitializeTimerEx": 2, "KeInsertQueueDpc": 3,
    "KeQueryInterruptTime": 0, "KeQueryPerformanceCounter": 0, "KeQueryPerformanceFrequency": 0, "KeQuerySystemTime": 1,
    "KeRaiseIrqlToDpcLevel": 0, "KeRemoveQueueDpc": 1, "KeRestoreFloatingPointState": 1, "KeSaveFloatingPointState": 1,
    "KeSetEvent": 3, "KeSetTimer": 3, "KeStallExecutionProcessor": 1, "KeWaitForMultipleObjects": 8, "KeWaitForSingleObject": 5,
    "KfLowerIrql": 0, "KfRaiseIrql": 0, "MmAllocateContiguousMemory": 1, "MmAllocateContiguousMemoryEx": 5,
    "MmAllocateSystemMemory": 2, "MmFreeContiguousMemory": 1, "MmFreeSystemMemory": 2, "MmGetPhysicalAddress": 1,
    "MmLockUnlockBufferPages": 3, "MmLockUnlockPhysicalPage": 2, "MmPersistContiguousMemory": 3, "MmQueryAllocationSize": 1,
    "MmQueryStatistics": 1, "NtAllocateVirtualMemory": 5, "NtClose": 1, "NtCreateFile": 9, "NtCreateMutant": 3,
    "NtFlushBuffersFile": 2, "NtFreeVirtualMemory": 3, "NtFsControlFile": 8, "NtOpenFile": 6, "NtOpenSymbolicLinkObject": 2,
    "NtQueryDirectoryFile": 7, "NtQueryFullAttributesFile": 2, "NtQueryInformationFile": 5, "NtQuerySymbolicLinkObject": 3,
    "NtQueryVolumeInformationFile": 5, "NtReadFile": 8, "NtReleaseMutant": 2, "NtResumeThread": 2, "NtSetEvent": 2,
    "NtSetInformationFile": 5, "NtWaitForMultipleObjectsEx": 6, "NtWaitForSingleObject": 3, "NtWaitForSingleObjectEx": 4,
    "NtWriteFile": 8, "ObReferenceObjectByHandle": 3, "ObfDereferenceObject": 0, "PhyGetLinkState": 1, "PhyInitialize": 2,
    "PsCreateSystemThreadEx": 10, "PsTerminateSystemThread": 1, "RtlCompareMemoryUlong": 3, "RtlEnterCriticalSection": 1,
    "RtlEqualString": 3, "RtlInitAnsiString": 2, "RtlInitializeCriticalSection": 1, "RtlLeaveCriticalSection": 1,
    "RtlNtStatusToDosError": 1, "RtlRaiseException": 1, "RtlTimeFieldsToTime": 2, "RtlTimeToTimeFields": 2,
    "RtlUnicodeStringToAnsiString": 3, "XeLoadSection": 1, "XeUnloadSection": 1,
    "NtCreateEvent": 5, "NtClearEvent": 1, "NtPulseEvent": 2, "NtQueryEvent": 2, "NtDuplicateObject": 3, "NtYieldExecution": 0,
    "NtSuspendThread": 2, "NtDeviceIoControlFile": 10, "NtQueryVirtualMemory": 3, "NtProtectVirtualMemory": 4,
    "KeInitializeEvent": 3, "KeResetEvent": 1, "KePulseEvent": 3, "KeInitializeSemaphore": 3, "KeReleaseSemaphore": 4,
    "KeSetBasePriorityThread": 2, "KeSetPriorityThread": 2, "KeQueryBasePriorityThread": 1, "KeGetCurrentThread": 0,
    "KeGetCurrentIrql": 0, "KeIsExecutingDpc": 0, "KeSetTimerEx": 4, "KeSetDisableBoostThread": 2, "KeBoostPriorityThread": 2,
    "KeEnterCriticalRegion": 0, "KeLeaveCriticalRegion": 0, "KeSuspendThread": 1, "KeResumeThread": 1, "KeAlertThread": 2,
    "KeTestAlertThread": 1, "KeSetEventBoostPriority": 2, "KeInitializeMutant": 2, "KeReleaseMutant": 4,
    "RtlInitUnicodeString": 2, "RtlZeroMemory": 2, "RtlFillMemory": 3, "RtlMoveMemory": 3, "RtlCompareMemory": 3,
    "RtlAnsiStringToUnicodeString": 3, "RtlFreeAnsiString": 1, "RtlFreeUnicodeString": 1, "RtlSnprintf": 3, "RtlSprintf": 2,
    "RtlVsnprintf": 4, "RtlVsprintf": 3, "RtlTryEnterCriticalSection": 1, "RtlEnterCriticalSectionAndRegion": 1,
    "RtlLeaveCriticalSectionAndRegion": 1, "RtlCaptureContext": 1, "RtlUnwind": 4, "RtlAssert": 4, "RtlRaiseStatus": 1,
    "RtlLowerChar": 1, "RtlUpperChar": 1, "RtlEqualUnicodeString": 3, "RtlCompareString": 3, "RtlCompareUnicodeString": 3,
    "RtlUpcaseUnicodeChar": 1, "RtlDowncaseUnicodeChar": 1, "RtlUnicodeToMultiByteN": 5, "RtlMultiByteToUnicodeN": 5,
    "RtlUnicodeStringToInteger": 3, "RtlCharToInteger": 3, "RtlIntegerToChar": 4, "RtlExtendedIntegerMultiply": 3,
    "RtlExtendedLargeIntegerDivide": 4, "RtlExtendedMagicDivide": 5, "RtlUlongByteSwap": 1, "RtlUshortByteSwap": 1,
    "DbgPrint": 1, "DbgBreakPoint": 0, "HalReadSMBusValue": 4, "HalWriteSMBusValue": 4, "HalReadSMCTrayState": 2,
    "AvSetDisplayMode": 6, "AvGetSavedDataAddress": 0, "AvSetSavedDataAddress": 1, "AvSendTVEncoderOption": 4,
    "MmMapIoSpace": 3, "MmUnmapIoSpace": 2, "MmIsAddressValid": 1, "MmSetAddressProtect": 3, "MmQueryAddressProtect": 1,
    "MmClaimGpuInstanceMemory": 2, "MmCreateKernelStack": 2, "MmDeleteKernelStack": 2, "MmDbgAllocateMemory": 2,
    "ExQueryNonVolatileSetting": 5, "ExSaveNonVolatileSetting": 4, "ExInitializeReadWriteLock": 1,
    "ExAcquireReadWriteLockExclusive": 1, "ExAcquireReadWriteLockShared": 1, "ExReleaseReadWriteLock": 1,
    "ExRaiseException": 1, "ExRaiseStatus": 1, "IoCreateDevice": 6, "IoCreateFile": 10, "IoDeleteSymbolicLink": 1,
    "IoDismountVolume": 1, "IoDismountVolumeByName": 1, "IoQueryFileInformation": 5, "IoQueryVolumeInformation": 5,
    "IoSynchronousDeviceIoControlRequest": 8, "IoSynchronousFsdRequest": 5, "ObCreateObject": 4, "ObInsertObject": 4,
    "ObMakeTemporaryObject": 1, "ObOpenObjectByName": 4, "ObOpenObjectByPointer": 3, "ObReferenceObjectByName": 5,
    "ObReferenceObjectByPointer": 2, "PsCreateSystemThread": 7, "PsQueryStatistics": 1, "PsSetCreateThreadNotifyRoutine": 1,
    "XcSHAInit": 1, "XcSHAUpdate": 3, "XcSHAFinal": 2, "XcRC4Key": 3, "XcRC4Crypt": 3, "XcHMAC": 7, "XcPKEncPublic": 3,
    "XcPKDecPrivate": 3, "XcPKGetKeyLen": 1, "XcVerifyPKCS1Signature": 3, "XcModExp": 5, "XcDESKeyParity": 2,
    "XcKeyTable": 3, "XcBlockCrypt": 5, "XcBlockCryptCBC": 7, "XcCryptService": 2, "XcUpdateCrypto": 2,
    "FscGetCacheSize": 0, "FscSetCacheSize": 1, "FscInvalidateIdleBlocks": 0, "HalEnableSecureTrayEject": 0,
    "HalIsResetOrShutdownPending": 0, "HalWriteSMCScratchRegister": 1, "HalReadWritePCISpace": 6,
    "HalDisableSystemInterrupt": 1, "HalEnableSystemInterrupt": 2, "HalRequestSoftwareInterrupt": 1, "HalClearSoftwareInterrupt": 1,
    "InterlockedCompareExchange": 0, "InterlockedDecrement": 0, "InterlockedIncrement": 0, "InterlockedExchange": 0,
    "InterlockedExchangeAdd": 0, "InterlockedFlushSList": 0, "InterlockedPopEntrySList": 0, "InterlockedPushEntrySList": 0,
    "ExfInterlockedInsertHeadList": 0, "ExfInterlockedInsertTailList": 0, "ExfInterlockedRemoveHeadList": 0,
    "ExInterlockedAddLargeInteger": 0, "ExInterlockedAddLargeStatistic": 0, "ExInterlockedCompareExchange64": 0,
    "IofCallDriver": 0, "IofCompleteRequest": 0, "ObfReferenceObject": 0, "KiUnlockDispatcherDatabase": 0,
}
