/*
 * xv_x86rt.h - runtime support for code generated by xita_recomp.py (Stage 4).
 * Hand-written; the generated files only include this header.
 */
#pragma once
#include <stdint.h>
#include <string.h>
#include <math.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Guest memory: arena (64 MB physical RAM + XBE image copy + trash page) addressed through a 4 KB page
 * table (virtual page -> arena offset).  0x80000000/0xF0000000 alias physical memory; the XBE image lives in
 * its own pages because Halo places physical allocations at the same numbers (see kernel/xk_mem.c). */
extern uint8_t  *g_xram;
extern uint32_t *g_xpt;
#if defined(XV_THREAD_PAGE_TABLE) && XV_THREAD_PAGE_TABLE && defined(__vita__)
/* Per-thread page table: every thread's TPIDRURW (user read/write thread-ID register, preserved per
 * thread by the kernel, otherwise unused - handoff 20260920 §25) holds the table it translates through.
 * runtime/xv_thread_bind.c binds it at thread start (live table today; a render thread gets its own
 * copy-on-write table later). The asm is not volatile, so GCC hoists it: one mrc per function. */
static inline uint32_t *xv_thread_page_table(void) { uint32_t v; __asm__("mrc p15, 0, %0, c13, c0, 2" : "=r"(v)); return (uint32_t *)v; }
#define X_PT (xv_thread_page_table())
#else
#define X_PT g_xpt
#endif
#ifdef XV_CHECK_GUEST_ADDRESS
/* Optional diagnostic target policy, invoked before translating a guest
 * pointer. This is not a memory-range validator: callers retain their normal
 * width/page handling, and image-constant accesses use the pinned image path.
 * Ordinary builds retain the original macro with no callback overhead. */
void xv_check_guest_address(uint32_t address);
/* The strict policy only ever acts on two address classes: the MMIO apertures at
 * 0xFD000000 and above, and pages that translate to the arena's trash page (the
 * unmapped-stack window). Both are decided here from values already in hand, so the
 * common access costs two compares; the policy function itself is unchanged and
 * still makes every decision on the slow path. */
extern uint32_t xv_trash_off;
#define XV_ADDRESS_NEEDS_POLICY(address, off) ((off) == xv_trash_off || (address) >= 0xFD000000u)
/* Write-epoch tracking (checked builds): every guest access stamps its arena page
 * with the current epoch (loads too - conservative), host writers stamp through
 * xv_mark_written, and the epoch advances once per presented frame. A consumer
 * that caches derived data (the texture cache) can prove "no write since my last
 * full read" from the stamps instead of re-reading megabytes every draw. */
#define XV_PAGE_EPOCH_ENTRIES 65536u          /* arena pages covered (256 MB); checked at bind */
extern uint32_t xv_page_epoch[XV_PAGE_EPOCH_ENTRIES];
extern uint32_t xv_page_count, xv_write_epoch;
void xv_mark_written(const void *host, uint32_t bytes);
/* Diagnostic write watch on an arena-offset range (XV_WATCH_PHYS=hex:hexlen). */
extern uint32_t xv_watch_off, xv_watch_len;
void xv_watch_store(uint32_t address, uint32_t off);
static inline void *x_guest_checked_pointer(uint32_t address)
{
    uint32_t off = X_PT[address >> 12];
    if (__builtin_expect(XV_ADDRESS_NEEDS_POLICY(address, off), 0)) { xv_check_guest_address(address); off = X_PT[address >> 12]; }
    return g_xram + off + (address & 0xFFFu);
}
/* Stores only: the recompiler emits X_W* for memory lvalues, X_M* for loads. */
static inline void *x_guest_checked_pointer_write(uint32_t address)
{
    uint32_t off = X_PT[address >> 12];
    if (__builtin_expect(XV_ADDRESS_NEEDS_POLICY(address, off), 0)) { xv_check_guest_address(address); off = X_PT[address >> 12]; }
    xv_page_epoch[off >> 12] = xv_write_epoch;
    if ((off + (address & 0xFFFu)) - xv_watch_off < xv_watch_len) xv_watch_store(address, off + (address & 0xFFFu));
    return g_xram + off + (address & 0xFFFu);
}
/* Host writes of n bytes through one translated pointer (the callers rely on
 * contiguous mapping of that span): every page of the span goes through the address
 * policy (a guarded colour-buffer page must be landed before it is overwritten, even
 * when the span starts outside it) and is stamped. */
static inline void *x_guest_checked_span_write(uint32_t address, uint32_t bytes)
{
    void *pointer = x_guest_checked_pointer_write(address);
    if (bytes > 1)
        for (uint32_t page = (address | 0xFFFu) + 1u; page - address < bytes - 1u && page > address; page += 0x1000u)
            (void)x_guest_checked_pointer_write(page);
    xv_mark_written(pointer, bytes);
    return pointer;
}
#define X_G(a)      x_guest_checked_pointer((uint32_t)(a))
#define X_GW(a)     x_guest_checked_pointer_write((uint32_t)(a))
#define X_GWN(a, n) x_guest_checked_span_write((uint32_t)(a), (uint32_t)(n))
#else
#define X_G(a)      ((void *)(g_xram + X_PT[(uint32_t)(a) >> 12] + ((uint32_t)(a) & 0xFFFu)))
#define X_GW(a)     X_G(a)
#define X_GWN(a, n) X_G(a)
#endif
/* Host copies must translate every guest page, including separately committed pages. */
void x_guest_read_pages(void *dst, uint32_t a, size_t size);
void x_guest_write_pages(uint32_t a, const void *src, size_t size);
/* Keep fixed-size, single-page accesses visible to the compiler. Including the
 * split-copy loop here made GCC emit calls to generic memcpy even for x87 floats. */
static inline __attribute__((always_inline)) void x_guest_read(void *dst, uint32_t a, size_t size)
{
    if (size <= 4096u - (a & 0xFFFu)) { memcpy(dst, X_G(a), size); return; }
    x_guest_read_pages(dst, a, size);
}
static inline __attribute__((always_inline)) void x_guest_write(uint32_t a, const void *src, size_t size)
{
    if (size <= 4096u - (a & 0xFFFu)) { memcpy(X_GW(a), src, size); return; }
    x_guest_write_pages(a, src, size);
}
/* x86 code reads and writes at any alignment.  On the Vita's Cortex-A9 plain ldr/str tolerate that, but
 * ldrd/strd and the VFP vldr/vstr do not (data abort: a10 load crashed on `fld dword [esi+6]` at an
 * address ending in ...5E).  Under-aligned types make GCC emit only alignment-safe sequences. */
typedef uint16_t __attribute__((aligned(1), may_alias)) xu16_u;
typedef uint32_t __attribute__((aligned(1), may_alias)) xu32_u;
typedef uint64_t __attribute__((aligned(1), may_alias)) xu64_u;
typedef float    __attribute__((aligned(1), may_alias)) xf32_u;
#define X_M8(a)     (*(uint8_t  *)X_G(a))
#define X_M16(a)    (*(xu16_u   *)X_G(a))
#define X_M32(a)    (*(xu32_u   *)X_G(a))
#define X_M64(a)    (*(xu64_u   *)X_G(a))
#define X_MF32(a)   (*(xf32_u   *)X_G(a))
/* Memory lvalues (stores): identical access, plus the page write stamp in checked builds. */
#define X_W8(a)     (*(uint8_t  *)X_GW(a))
#define X_W16(a)    (*(xu16_u   *)X_GW(a))
#define X_W32(a)    (*(xu32_u   *)X_GW(a))
#define X_W64(a)    (*(xu64_u   *)X_GW(a))
#define X_WF32(a)   (*(xf32_u   *)X_GW(a))
/* Fast path for constant addresses in the XBE image: the image is copied once into the arena at a fixed
 * offset (arena base XRAM_SIZE, virtual base g_image_lo) and is never remapped, so its host pointer is a
 * compile-time-constant-plus-base with no page-table load.  g_img_base = g_xram + XRAM_SIZE - g_image_lo,
 * set in xk_mem_setup; the recompiler emits X_IMG* only for constant displacements inside [image_lo,hi). */
extern uint8_t *g_img_base;
#define X_IMG8(a)   (*(uint8_t  *)(g_img_base + (uint32_t)(a)))
#define X_IMG16(a)  (*(xu16_u   *)(g_img_base + (uint32_t)(a)))
#define X_IMG32(a)  (*(xu32_u   *)(g_img_base + (uint32_t)(a)))

enum { XK_LOGIC = 0, XK_ADD, XK_ADC, XK_SUB, XK_SBB, XK_EXPLICIT };

typedef struct xctx {
    uint32_t r[8];                 /* eax ecx edx ebx esp ebp esi edi */
    uint32_t fs_base;              /* fs:[..] base (per-fiber KPCR/TIB) */
    uint32_t df;                   /* direction flag */
    /* lazy flags */
    uint32_t f_kind, f_op1, f_op2, f_res, f_bits, f_cf_override, f_cf, f_of_override, f_of;
    /* x87 */
    double   st[8];
    uint32_t fsp;
    uint16_t fsw, fcw;
    /* MMX (kept separate from the x87 stack; MSVC/Bink code never relies on aliasing) */
    uint64_t mm[8];
    uint32_t scratch;              /* sink for writes to segment registers etc. */
    /* SSE */
    float    xmm[8][4];
    /* bookkeeping */
    int32_t  preempt;              /* back-edge budget; xv_preempt() refills and yields (spin-loop starvation fix) */
    uint32_t eip_hint;
    void    *fiber;                /* owning xk fiber */
#if defined(XV_EFLAGS_ID) && XV_EFLAGS_ID
    uint32_t id_flag;              /* EFLAGS.ID, independent of lazy arithmetic flags */
#endif
} xctx;

#define X_R16(i)    (*(uint16_t *)&c->r[i])
#define X_R8L(i)    (*(uint8_t  *)&c->r[i])
#define X_R8H(i)    (*((uint8_t *)&c->r[i] + 1))

#define X_PUSH32(v) do { uint32_t v__ = (uint32_t)(v); c->r[4] -= 4; X_W32(c->r[4]) = v__; } while (0)
static inline uint32_t x_pop32(xctx *c) { uint32_t v = X_M32(c->r[4]); c->r[4] += 4; return v; }
#define X_POP32()   x_pop32(c)
/* HLE/kernel implementations: stack argument n (0-based) and stdcall return */
#define X_ARG(n)    X_M32(c->r[4] + 4u + 4u * (n))
#define X_RET(nargs) do { c->r[4] += 4u + 4u * (nargs); return; } while (0)

/* ---- flags ---------------------------------------------------------------------- */
#define X_FLAGS(kind, op1, op2, res, bits) do { c->f_kind = (kind); c->f_op1 = (uint32_t)(op1); c->f_op2 = (uint32_t)(op2); \
        c->f_res = (uint32_t)(res); c->f_bits = (bits); c->f_cf_override = 0; c->f_of_override = 0; } while (0)
#define X_FLAGS_C(kind, op1, op2, res, bits, cfin) do { X_FLAGS(kind, op1, op2, res, bits); c->f_cf = (cfin); } while (0)

/* inline flag evaluation for fused cmp/test/arith + jcc (constant bits fold at compile time) */
#define XFI_MASK(bits)          ((bits) == 32 ? 0xFFFFFFFFu : ((1u << (bits)) - 1u))
#define XFI_MSB(v, bits)        ((((uint32_t)(v)) >> ((bits) - 1)) & 1u)
#define XFI_Z(r, bits)          ((((uint32_t)(r)) & XFI_MASK(bits)) == 0)
#define XFI_S(r, bits)          XFI_MSB(r, bits)
#define XFI_C_SUB(a, b, bits)   ((((uint32_t)(a)) & XFI_MASK(bits)) < (((uint32_t)(b)) & XFI_MASK(bits)))
#define XFI_C_ADD(a, r, bits)   ((((uint32_t)(r)) & XFI_MASK(bits)) < (((uint32_t)(a)) & XFI_MASK(bits)))
#define XFI_O_SUB(a, b, r, bits) XFI_MSB(((a) ^ (b)) & ((a) ^ (r)), bits)
#define XFI_O_ADD(a, b, r, bits) XFI_MSB(((a) ^ (r)) & ((b) ^ (r)), bits)
static inline uint32_t xf_mask(const xctx *c) { return c->f_bits == 32 ? 0xFFFFFFFFu : ((1u << c->f_bits) - 1u); }
static inline uint32_t xf_msb(const xctx *c, uint32_t v) { return (v >> (c->f_bits - 1)) & 1u; }

static inline uint32_t XF_Z(const xctx *c) {
    if (c->f_kind == XK_EXPLICIT) return (c->f_res >> 6) & 1u;
    return (c->f_res & xf_mask(c)) == 0;
}
static inline uint32_t XF_S(const xctx *c) {
    if (c->f_kind == XK_EXPLICIT) return (c->f_res >> 7) & 1u;
    return xf_msb(c, c->f_res);
}
static inline uint32_t XF_P(const xctx *c) {
    if (c->f_kind == XK_EXPLICIT) return (c->f_res >> 2) & 1u;
    return (__builtin_popcount(c->f_res & 0xFFu) & 1u) == 0;
}
static inline uint32_t XF_C(const xctx *c) {
    if (c->f_kind == XK_EXPLICIT) return c->f_res & 1u;
    if (c->f_cf_override) return c->f_cf;
    uint32_t m = xf_mask(c), a = c->f_op1 & m, b = c->f_op2 & m, r = c->f_res & m;
    switch (c->f_kind) {
    case XK_ADD: return r < a;
    case XK_ADC: return c->f_cf ? (r <= a) : (r < a);
    case XK_SUB: return a < b;
    case XK_SBB: return c->f_cf ? (a <= b) : (a < b);
    default:     return 0;
    }
}
static inline uint32_t XF_O(const xctx *c) {
    if (c->f_kind == XK_EXPLICIT) return (c->f_res >> 11) & 1u;
    if (c->f_of_override) return c->f_of;
    uint32_t a = c->f_op1, b = c->f_op2, r = c->f_res;
    switch (c->f_kind) {
    case XK_ADD: case XK_ADC: return xf_msb(c, (a ^ r) & (b ^ r));
    case XK_SUB: case XK_SBB: return xf_msb(c, (a ^ b) & (a ^ r));
    default: return 0;
    }
}
static inline uint32_t xf_eflags(xctx *c) {
    uint32_t value = 0x202u | XF_C(c) | (XF_P(c) << 2) | (XF_Z(c) << 6) | (XF_S(c) << 7) | (XF_O(c) << 11) | (c->df << 10);
#if defined(XV_EFLAGS_ID) && XV_EFLAGS_ID
    value |= c->id_flag & 0x200000u;
#endif
    return value;
}
static inline void xf_set_eflags(xctx *c, uint32_t v) {
    c->f_kind = XK_EXPLICIT; c->f_res = v; c->f_bits = 32; c->f_cf_override = 0; c->f_of_override = 0; c->df = (v >> 10) & 1u;
#if defined(XV_EFLAGS_ID) && XV_EFLAGS_ID
    c->id_flag = v & 0x200000u;
#endif
}

/* ---- shifts / rotates ------------------------------------------------------------- */
#define X_DEF_SHIFTS(B, T)                                                                              \
static inline T x_shl##B(xctx *c, T v, uint32_t n) { n &= 31; if (!n) return v; if (n > B) n = B;      \
    T r = (T)((uint32_t)v << n); X_FLAGS(XK_LOGIC, 0, 0, r, B); c->f_cf_override = 1;                   \
    c->f_cf = n <= B ? ((uint32_t)v >> (B - n)) & 1u : 0; c->f_of_override = 1; c->f_of = (r >> (B-1) & 1u) ^ c->f_cf; return r; } \
static inline T x_shr##B(xctx *c, T v, uint32_t n) { n &= 31; if (!n) return v; T r = n >= B ? 0 : (T)((uint32_t)v >> n);  \
    X_FLAGS(XK_LOGIC, 0, 0, r, B); c->f_cf_override = 1; c->f_cf = n <= B ? ((uint32_t)v >> (n - 1)) & 1u : 0;              \
    c->f_of_override = 1; c->f_of = ((uint32_t)v >> (B - 1)) & 1u; return r; }                                             \
static inline T x_sar##B(xctx *c, T v, uint32_t n) { n &= 31; if (!n) return v; if (n > B - 1) n = B - 1 + ((n>=B)?0:0);   \
    int32_t sv = (int32_t)(int##B##_t)v; T r = (T)(sv >> (n >= B ? B - 1 : n)); if (n >= B) r = sv < 0 ? (T)~(T)0 : 0;     \
    X_FLAGS(XK_LOGIC, 0, 0, r, B); c->f_cf_override = 1; c->f_cf = (uint32_t)(sv >> ((n >= B ? B : n) - 1)) & 1u;          \
    c->f_of_override = 1; c->f_of = 0; return r; }                                                                          \
static inline T x_rol##B(xctx *c, T v, uint32_t n) { n &= 31; uint32_t m = n % B; T r = m ? (T)(((uint32_t)v << m) | ((uint32_t)v >> (B - m))) : v; \
    if (n) { c->f_cf_override = 1; c->f_cf = r & 1u; c->f_of_override = 1; c->f_of = ((r >> (B-1)) & 1u) ^ (r & 1u); } return r; } \
static inline T x_ror##B(xctx *c, T v, uint32_t n) { n &= 31; uint32_t m = n % B; T r = m ? (T)(((uint32_t)v >> m) | ((uint32_t)v << (B - m))) : v; \
    if (n) { c->f_cf_override = 1; c->f_cf = (r >> (B-1)) & 1u; c->f_of_override = 1; c->f_of = ((r >> (B-1)) ^ (r >> (B-2))) & 1u; } return r; } \
static inline T x_rcl##B(xctx *c, T v, uint32_t n) { n &= 31; n %= (B + 1); uint32_t cf = XF_C(c); uint64_t w = ((uint64_t)cf << B) | v; \
    for (uint32_t i = 0; i < n; ++i) { w = ((w << 1) | (w >> B)) & (((uint64_t)1 << (B + 1)) - 1); } c->f_cf_override = 1; c->f_cf = (uint32_t)(w >> B) & 1u; \
    c->f_of_override = 1; c->f_of = 0; return (T)w; }                                                                       \
static inline T x_rcr##B(xctx *c, T v, uint32_t n) { n &= 31; n %= (B + 1); uint32_t cf = XF_C(c); uint64_t w = ((uint64_t)cf << B) | v; \
    for (uint32_t i = 0; i < n; ++i) { w = ((w >> 1) | ((w & 1) << B)) & (((uint64_t)1 << (B + 1)) - 1); } c->f_cf_override = 1; c->f_cf = (uint32_t)(w >> B) & 1u; \
    c->f_of_override = 1; c->f_of = 0; return (T)w; }
X_DEF_SHIFTS(8, uint8_t)
X_DEF_SHIFTS(16, uint16_t)
X_DEF_SHIFTS(32, uint32_t)

static inline uint32_t x_shld(xctx *c, uint32_t a, uint32_t b, uint32_t n) { n &= 31; if (!n) return a;
    uint32_t r = (a << n) | (b >> (32 - n)); X_FLAGS(XK_LOGIC, 0, 0, r, 32); c->f_cf_override = 1; c->f_cf = (a >> (32 - n)) & 1u; return r; }
static inline uint32_t x_shrd(xctx *c, uint32_t a, uint32_t b, uint32_t n) { n &= 31; if (!n) return a;
    uint32_t r = (a >> n) | (b << (32 - n)); X_FLAGS(XK_LOGIC, 0, 0, r, 32); c->f_cf_override = 1; c->f_cf = (a >> (n - 1)) & 1u; return r; }

/* ---- multiply / divide ----------------------------------------------------------- */
static inline uint32_t x_imul32(xctx *c, uint32_t a, uint32_t b) { int64_t p = (int64_t)(int32_t)a * (int32_t)b; uint32_t r = (uint32_t)p;
    X_FLAGS(XK_LOGIC, 0, 0, r, 32); c->f_cf_override = c->f_of_override = 1; c->f_cf = c->f_of = (p != (int64_t)(int32_t)r); return r; }
static inline uint16_t x_imul16(xctx *c, uint16_t a, uint16_t b) { int32_t p = (int32_t)(int16_t)a * (int16_t)b; uint16_t r = (uint16_t)p;
    X_FLAGS(XK_LOGIC, 0, 0, r, 16); c->f_cf_override = c->f_of_override = 1; c->f_cf = c->f_of = (p != (int32_t)(int16_t)r); return r; }
static inline void x_imul1_32(xctx *c, uint32_t a) { int64_t p = (int64_t)(int32_t)c->r[0] * (int32_t)a; c->r[0] = (uint32_t)p; c->r[2] = (uint32_t)((uint64_t)p >> 32);
    X_FLAGS(XK_LOGIC, 0, 0, c->r[0], 32); c->f_cf_override = c->f_of_override = 1; c->f_cf = c->f_of = (p != (int64_t)(int32_t)c->r[0]); }
static inline void x_imul1_16(xctx *c, uint16_t a) { int32_t p = (int32_t)(int16_t)X_R16(0) * (int16_t)a; X_R16(0) = (uint16_t)p; X_R16(2) = (uint16_t)((uint32_t)p >> 16);
    X_FLAGS(XK_LOGIC, 0, 0, (uint16_t)p, 16); c->f_cf_override = c->f_of_override = 1; c->f_cf = c->f_of = (p != (int32_t)(int16_t)p); }
static inline void x_imul1_8(xctx *c, uint8_t a) { int16_t p = (int16_t)((int8_t)X_R8L(0) * (int8_t)a); X_R16(0) = (uint16_t)p;
    X_FLAGS(XK_LOGIC, 0, 0, (uint8_t)p, 8); c->f_cf_override = c->f_of_override = 1; c->f_cf = c->f_of = (p != (int16_t)(int8_t)p); }
static inline void x_mul_32(xctx *c, uint32_t a) { uint64_t p = (uint64_t)c->r[0] * a; c->r[0] = (uint32_t)p; c->r[2] = (uint32_t)(p >> 32);
    X_FLAGS(XK_LOGIC, 0, 0, c->r[0], 32); c->f_cf_override = c->f_of_override = 1; c->f_cf = c->f_of = c->r[2] != 0; }
static inline void x_mul_16(xctx *c, uint16_t a) { uint32_t p = (uint32_t)X_R16(0) * a; X_R16(0) = (uint16_t)p; X_R16(2) = (uint16_t)(p >> 16);
    X_FLAGS(XK_LOGIC, 0, 0, (uint16_t)p, 16); c->f_cf_override = c->f_of_override = 1; c->f_cf = c->f_of = (p >> 16) != 0; }
static inline void x_mul_8(xctx *c, uint8_t a) { uint16_t p = (uint16_t)X_R8L(0) * a; X_R16(0) = p;
    X_FLAGS(XK_LOGIC, 0, 0, (uint8_t)p, 8); c->f_cf_override = c->f_of_override = 1; c->f_cf = c->f_of = (p >> 8) != 0; }

void xv_trap(xctx *c, uint32_t eip);                 /* fatal: #DE, int3, unreachable */
void xv_preempt(xctx *c);                            /* called when the back-edge budget runs out */
#define X_PREEMPT() do { if (--c->preempt <= 0) xv_preempt(c); } while (0)
void xv_unimpl(xctx *c, uint32_t eip, const char *what);

static inline void x_div_32(xctx *c, uint32_t a, uint32_t eip)
{
    uint32_t lo = c->r[0], hi = c->r[2];
    /* hi >= divisor is exactly the unsigned quotient-overflow condition. */
    if (!a || hi >= a) { xv_trap(c, eip); return; }
    if (!hi) {
        /* The usual XOR EDX,EDX case needs only 32-bit software division. */
        c->r[0] = lo / a;
        c->r[2] = lo % a;
        return;
    }
    uint64_t n = ((uint64_t)hi << 32) | lo;
    c->r[0] = (uint32_t)(n / a);
    c->r[2] = (uint32_t)(n % a);
}
static inline void x_idiv_32(xctx *c, uint32_t a, uint32_t eip)
{
    uint32_t lo = c->r[0], hi = c->r[2];
    int32_t divisor = (int32_t)a, low = (int32_t)lo;
    if (!a) { xv_trap(c, eip); return; }
    if (hi == (low < 0 ? UINT32_MAX : 0u)) {
        /* CDQ produces a signed 32-bit dividend. Guard C's overflow case
         * before dividing, and leave the guest context intact on a trap. */
        if (low == INT32_MIN && divisor == -1) { xv_trap(c, eip); return; }
        c->r[0] = (uint32_t)(low / divisor);
        c->r[2] = (uint32_t)(low % divisor);
        return;
    }
    int64_t n = (int64_t)(((uint64_t)hi << 32) | lo);
    if (n == INT64_MIN && divisor == -1) { xv_trap(c, eip); return; }
    int64_t q = n / divisor;
    if (q < INT32_MIN || q > INT32_MAX) { xv_trap(c, eip); return; }
    c->r[0] = (uint32_t)(int32_t)q;
    c->r[2] = (uint32_t)(int32_t)(n % divisor);
}
static inline void x_div_16(xctx *c, uint16_t a, uint32_t eip) { if (!a) { xv_trap(c, eip); return; }
    uint32_t n = ((uint32_t)X_R16(2) << 16) | X_R16(0); X_R16(0) = (uint16_t)(n / a); X_R16(2) = (uint16_t)(n % a); }
static inline void x_idiv_16(xctx *c, uint16_t a, uint32_t eip) { if (!a) { xv_trap(c, eip); return; }
    int32_t n = (int32_t)(((uint32_t)X_R16(2) << 16) | X_R16(0)); X_R16(0) = (uint16_t)(n / (int16_t)a); X_R16(2) = (uint16_t)(n % (int16_t)a); }
static inline void x_div_8(xctx *c, uint8_t a, uint32_t eip) { if (!a) { xv_trap(c, eip); return; }
    uint16_t n = X_R16(0); X_R8L(0) = (uint8_t)(n / a); X_R8H(0) = (uint8_t)(n % a); }
static inline void x_idiv_8(xctx *c, uint8_t a, uint32_t eip) { if (!a) { xv_trap(c, eip); return; }
    int16_t n = (int16_t)X_R16(0); X_R8L(0) = (uint8_t)(n / (int8_t)a); X_R8H(0) = (uint8_t)(n % (int8_t)a); }

/* ---- string instructions ------------------------------------------------------------ */
enum { X_STR_ONCE = 0, X_STR_REP, X_STR_REPE, X_STR_REPNE };
void x_str_movs(xctx *c, unsigned sz, int mode);
void x_str_stos(xctx *c, unsigned sz, int mode);
void x_str_lods(xctx *c, unsigned sz, int mode);
void x_str_cmps(xctx *c, unsigned sz, int mode);
void x_str_scas(xctx *c, unsigned sz, int mode);

/* ---- x87 -------------------------------------------------------------------------- */
#define X_ST(i)  (c->st[(c->fsp + (i)) & 7u])
static inline void x87_push(xctx *c, double v) { c->fsp = (c->fsp - 1u) & 7u; c->st[c->fsp] = v; }
static inline void x87_pop(xctx *c) { c->fsp = (c->fsp + 1u) & 7u; }
static inline void x87_init(xctx *c) { c->fsp = 0; c->fcw = 0x037F; c->fsw = 0; }
static inline double x87_load_f32(xctx *c, uint32_t a) { (void)c; float v; x_guest_read(&v, a, 4); return (double)v; }
static inline double x87_load_f64(xctx *c, uint32_t a) { double d; (void)c; x_guest_read(&d, a, 8); return d; }
double x87_load_f80(xctx *c, uint32_t a);
static inline double x87_load_i16(xctx *c, uint32_t a) { (void)c; int16_t v; x_guest_read(&v, a, 2); return (double)v; }
static inline double x87_load_i32(xctx *c, uint32_t a) { (void)c; int32_t v; x_guest_read(&v, a, 4); return (double)v; }
static inline double x87_load_i64(xctx *c, uint32_t a) { int64_t v; (void)c; x_guest_read(&v, a, 8); return (double)v; }
static inline void x87_store_f32(xctx *c, uint32_t a, double v) { (void)c; float r = (float)v; x_guest_write(a, &r, 4); }
static inline void x87_store_f64(xctx *c, uint32_t a, double v) { (void)c; x_guest_write(a, &v, 8); }
void x87_store_f80(xctx *c, uint32_t a, double v);
static inline double x87_round(xctx *c, double v) {
    switch ((c->fcw >> 10) & 3u) { case 0: return nearbyint(v); case 1: return floor(v); case 2: return ceil(v); default: return trunc(v); }
}
static inline double x87_trunc(xctx *c, double v) { (void)c; return trunc(v); }
static inline void x87_store_i16(xctx *c, uint32_t a, double v) { (void)c; uint16_t r = (v >= -32768.0 && v <= 32767.0) ? (uint16_t)(int16_t)v : 0x8000u; x_guest_write(a, &r, 2); }
static inline void x87_store_i32(xctx *c, uint32_t a, double v) { (void)c; uint32_t r = (v >= -2147483648.0 && v <= 2147483647.0) ? (uint32_t)(int32_t)v : 0x80000000u; x_guest_write(a, &r, 4); }
static inline void x87_store_i64(xctx *c, uint32_t a, double v) { int64_t r = (v >= -9.2233720368547758e18 && v < 9.2233720368547758e18) ? (int64_t)v : (int64_t)0x8000000000000000ull; (void)c; x_guest_write(a, &r, 8); }
static inline void x87_compare(xctx *c, double a, double b, int eflags) {
    uint16_t cc;
#if defined(__thumb2__) && defined(__ARM_FP) && (__ARM_FP & 8)
    /* One quiet VFP comparison provides unordered/less/equal together. The
     * portable expression otherwise emits up to three comparisons on A9.
     * Keep the guest condition codes and native FP exceptions unchanged. */
    uint32_t result;
    __asm__ volatile("vcmp.f64 %P1, %P2\n\tvmrs APSR_nzcv, fpscr\n\t"
                     "mov %0, #0\n\tit mi\n\tmovmi %0, #256\n\t"
                     "it eq\n\tmoveq %0, #16384\n\t"
                     "it vs\n\tmovvs %0, #17664"
                     : "=r"(result) : "w"(a), "w"(b) : "cc");
    cc = (uint16_t)result;
#else
    if (isnan(a) || isnan(b)) cc = 0x4500;                          /* C3|C2|C0 */
    else if (a < b)           cc = 0x0100;                          /* C0 */
    else if (a == b)          cc = 0x4000;                          /* C3 */
    else                      cc = 0;
#endif
    c->fsw = (uint16_t)((c->fsw & ~0x4700u) | cc | ((c->fsp & 7u) << 11));
    if (eflags) {                                                    /* fcomi: ZF=C3 PF=C2 CF=C0 */
        uint32_t f = ((cc & 0x4000) ? 0x40u : 0) | ((cc & 0x0400) ? 0x04u : 0) | ((cc & 0x0100) ? 0x01u : 0);
        xf_set_eflags(c, (xf_eflags(c) & ~0x45u) | f);
    }
}
static inline void x87_fxam(xctx *c) {
    double v = X_ST(0); uint16_t cc;
    if (isnan(v)) cc = 0x0100; else if (isinf(v)) cc = 0x0500; else if (v == 0.0) cc = 0x4000; else cc = 0x0400;
    if (signbit(v)) cc |= 0x0200;
    c->fsw = (uint16_t)((c->fsw & ~0x4700u) | cc);
}

/* ---- SSE helpers ----------------------------------------------------------------------- */
static inline void x_load128(xctx *c, float *d, uint32_t a) { (void)c; x_guest_read(d, a, 16); }
static inline void x_store128(xctx *c, uint32_t a, const float *s) { (void)c; x_guest_write(a, s, 16); }
static inline void x_comiss(xctx *c, float a, float b) {
    uint32_t f = (isnan(a) || isnan(b)) ? 0x45u : (a < b) ? 0x01u : (a == b) ? 0x40u : 0u;
    xf_set_eflags(c, (xf_eflags(c) & ~0x8D5u) | f);
}
static inline void x_bitops128(xctx *c, float *d, const float *s, char op) { (void)c;
    uint32_t a[4], b[4]; memcpy(a, d, 16); memcpy(b, s, 16);
    for (int i = 0; i < 4; ++i) a[i] = op == '^' ? a[i] ^ b[i] : op == '&' ? a[i] & b[i] : op == 'n' ? (~a[i]) & b[i] : a[i] | b[i];
    memcpy(d, a, 16); }
static inline void x_shufps(xctx *c, float *d, const float *s, unsigned imm) { (void)c;
    float t[4] = { d[imm & 3], d[(imm >> 2) & 3], s[(imm >> 4) & 3], s[(imm >> 6) & 3] }; memcpy(d, t, 16); }
static inline void x_unpcklps(xctx *c, float *d, const float *s) { (void)c; float t[4] = { d[0], s[0], d[1], s[1] }; memcpy(d, t, 16); }
static inline void x_unpckhps(xctx *c, float *d, const float *s) { (void)c; float t[4] = { d[2], s[2], d[3], s[3] }; memcpy(d, t, 16); }

/* Legacy CMPSS: only the low scalar participates, including in exceptions.
 * Any NaN takes priority over a denormal in the other operand. Predicates
 * 1/2/5/6 signal for QNaNs; every predicate signals for SNaNs. */
static inline uint32_t x_cmpss_bits(uint32_t a, uint32_t b, unsigned predicate,
                                   uint32_t *status)
{
    uint32_t aa = a & 0x7FFFFFFFu, bb = b & 0x7FFFFFFFu;
    int unordered = aa > 0x7F800000u || bb > 0x7F800000u;
    int equal = 0, less = 0;
    if (unordered) {
        if ((aa > 0x7F800000u && !(a & 0x00400000u)) ||
            (bb > 0x7F800000u && !(b & 0x00400000u)) ||
            predicate == 1 || predicate == 2 || predicate == 5 || predicate == 6)
            *status |= 1u;
    } else {
        if ((aa && aa < 0x00800000u) || (bb && bb < 0x00800000u)) *status |= 0x80u;
        equal = a == b || !(aa | bb);
        less = !equal && (((a ^ b) >> 31) ? (int)(a >> 31) : (a >> 31) ? a > b : a < b);
    }
    int result;
    switch (predicate) {
    case 0: result = equal; break;
    case 1: result = less; break;
    case 2: result = less || equal; break;
    case 3: result = unordered; break;
    case 4: result = !equal; break;
    case 5: result = !less; break;
    case 6: result = !(less || equal); break;
    case 7: result = !unordered; break;
    default: return 0; /* Reserved predicate: rejected by the public helper. */
    }
    return 0u - (uint32_t)result;
}
static inline int x_cmpss(float *destination, uint32_t source, unsigned predicate)
{
    if (predicate > 7) return 0; /* Reserved legacy encodings remain unsupported. */
#if defined(__arm__) && defined(__VFP_FP__)
    uint32_t fpscr, left, status = 0;
    __asm__ volatile("vmrs %0, fpscr" : "=r"(fpscr) :: "memory");
    if (fpscr & 0x03379F00u) return 0; /* Same supported controls as MINPS/MAXPS. */
    memcpy(&left, destination, 4);
    uint32_t result = x_cmpss_bits(left, source, predicate, &status);
    fpscr |= status;
    __asm__ volatile("vmsr fpscr, %0" :: "r"(fpscr) : "memory");
    memcpy(destination, &result, 4);
    return 1;
#elif defined(__SSE__)
    typedef float vector4 __attribute__((vector_size(16)));
    vector4 a, b = {0, 0, 0, 0};
    memcpy(&a, destination, 16); memcpy(&b, &source, 4);
#define X_CMPSS_CASE(N) case N: __asm__ volatile("cmpss $" #N ",%1,%0" : "+x"(a) : "x"(b) : "memory"); break
    switch (predicate) {
        X_CMPSS_CASE(0); X_CMPSS_CASE(1); X_CMPSS_CASE(2); X_CMPSS_CASE(3);
        X_CMPSS_CASE(4); X_CMPSS_CASE(5); X_CMPSS_CASE(6); X_CMPSS_CASE(7);
    }
#undef X_CMPSS_CASE
    memcpy(destination, &a, 4);
    return 1;
#else
    (void)destination; (void)source;
    return 0;
#endif
}
/* CMPPS: the scalar compare above applied to all four lanes (same predicate set, same
 * legacy exception rules per lane, same supported FP controls on ARM). Halo 2's level
 * loader uses cmpltps + movmskps for bounding tests (0x2FD2F9). */
static inline int x_cmpps(float *destination, const float *source, unsigned predicate)
{
    if (predicate > 7) return 0;
#if defined(__arm__) && defined(__VFP_FP__)
    uint32_t fpscr, left[4], right[4], result[4], status = 0;
    __asm__ volatile("vmrs %0, fpscr" : "=r"(fpscr) :: "memory");
    if (fpscr & 0x03379F00u) return 0;
    memcpy(left, destination, 16); memcpy(right, source, 16);
    for (unsigned i = 0; i < 4; ++i) result[i] = x_cmpss_bits(left[i], right[i], predicate, &status);
    fpscr |= status;
    __asm__ volatile("vmsr fpscr, %0" :: "r"(fpscr) : "memory");
    memcpy(destination, result, 16);
    return 1;
#elif defined(__SSE__)
    typedef float vector4 __attribute__((vector_size(16)));
    vector4 a, b;
    memcpy(&a, destination, 16); memcpy(&b, source, 16);
#define X_CMPPS_CASE(N) case N: __asm__ volatile("cmpps $" #N ",%1,%0" : "+x"(a) : "x"(b) : "memory"); break
    switch (predicate) {
        X_CMPPS_CASE(0); X_CMPPS_CASE(1); X_CMPPS_CASE(2); X_CMPPS_CASE(3);
        X_CMPPS_CASE(4); X_CMPPS_CASE(5); X_CMPPS_CASE(6); X_CMPPS_CASE(7);
    }
#undef X_CMPPS_CASE
    memcpy(destination, &a, 16);
    return 1;
#else
    uint32_t left[4], right[4], result[4], status = 0;
    memcpy(left, destination, 16); memcpy(right, source, 16);
    for (unsigned i = 0; i < 4; ++i) result[i] = x_cmpss_bits(left[i], right[i], predicate, &status);
    memcpy(destination, result, 16);
    return 1;
#endif
}
static inline uint32_t x_movmskps(const float *source)
{
    uint32_t bits[4]; memcpy(bits, source, 16);
    return (bits[0] >> 31) | ((bits[1] >> 30) & 2u) |
           ((bits[2] >> 29) & 4u) | ((bits[3] >> 28) & 8u);
}

/* Legacy MINPS/MAXPS select source two for NaNs and equal signed zeros.
 * Return its bits unchanged, including an SNaN payload. For a lane containing
 * a NaN, invalid has priority over denormal; other lanes still accumulate
 * their own status. Status uses ARM FPSCR IOC/IDC bits (0/7). */
static inline uint32_t x_minmax_bits(uint32_t a, uint32_t b, int maximum,
                                    uint32_t *status)
{
    uint32_t aa = a & 0x7FFFFFFFu, bb = b & 0x7FFFFFFFu;
    if (aa > 0x7F800000u || bb > 0x7F800000u) {
        *status |= 1u;
        return b;
    }
    if ((aa && aa < 0x00800000u) || (bb && bb < 0x00800000u)) *status |= 0x80u;
    if (!(aa | bb) || a == b) return b;
    int less = ((a ^ b) >> 31) ? (int)(a >> 31) : (a >> 31) ? a > b : a < b;
    return (maximum ? !less : less) ? a : b;
}
static inline int x_minmaxps(float *destination, const float *source, int maximum)
{
#if defined(__arm__) && defined(__VFP_FP__)
    uint32_t fpscr;
    __asm__ volatile("vmrs %0, fpscr" : "=r"(fpscr) :: "memory");
    /* No emulation of DN/FZ, vector Len/Stride or unmasked exceptions.
     * All rounding modes are valid: this instruction only selects bits.
     * H2's existing LDMXCSR adapter already enforces supported controls. */
    if (fpscr & 0x03379F00u) return 0;
    uint32_t a[4], b[4], status = 0;
    memcpy(a, destination, 16); memcpy(b, source, 16);
    for (unsigned lane = 0; lane < 4; ++lane)
        a[lane] = x_minmax_bits(a[lane], b[lane], maximum, &status);
    fpscr |= status;
    __asm__ volatile("vmsr fpscr, %0" :: "r"(fpscr) : "memory");
    memcpy(destination, a, 16);
    return 1;
#elif defined(__SSE__)
    typedef float vector4 __attribute__((vector_size(16)));
    vector4 a, b; memcpy(&a, destination, 16); memcpy(&b, source, 16);
    if (maximum) __asm__ volatile("maxps %1,%0" : "+x"(a) : "x"(b) : "memory");
    else __asm__ volatile("minps %1,%0" : "+x"(a) : "x"(b) : "memory");
    memcpy(destination, &a, 16);
    return 1;
#else
    (void)destination; (void)source; (void)maximum;
    return 0;
#endif
}

/* Legacy RSQRTPS: no FP exceptions and independent of the host rounding mode.
 * Integer Q30 Newton steps avoid modifying FPSCR/MXCSR even for signaling NaNs.
 * This meets Intel's relative-error bound, not a particular CPU's estimate bits.
 * Seeds are round(2^30 / sqrt(1 + (index + 0.5)/16)), not game data. */
static inline uint32_t x_rsqrt_bits(uint32_t bits)
{
    uint32_t exponent = (bits >> 23) & 255u, fraction = bits & 0x7FFFFFu;
    if (!exponent) return (bits & 0x80000000u) | 0x7F800000u;
    if (exponent == 255u && fraction) return bits | 0x00400000u;
    if (bits & 0x80000000u) return 0xFFC00000u;
    if (exponent == 255u) return 0;
    static const uint32_t seeds[16] = {
        1057347856u, 1026693558u, 998559613u, 972618566u,
        948599586u, 926276469u, 905458609u, 885984104u,
        867714429u, 850530263u, 834328203u, 819018128u,
        804521086u, 790767575u, 777696137u, 765252196u
    };
    uint64_t m = (uint64_t)(fraction | 0x800000u) << 7;
    uint64_t y = seeds[fraction >> 19];
    for (unsigned step = 0; step < 2; ++step) {
        uint64_t yy = (y * y) >> 30;
        y = (y * ((3ull << 30) - ((m * yy) >> 30))) >> 31;
    }
    int e = (int)exponent - 127;
    unsigned odd = (unsigned)(e + 126) & 1u;
    if (odd) y = (y * 759250125u) >> 30; /* round(2^30 / sqrt(2)) */
    unsigned output_exponent = (unsigned)(126 - (e - (int)odd) / 2);
    uint32_t significand = (uint32_t)((y + 32u) >> 6);
    if (significand == 0x1000000u) { significand >>= 1; ++output_exponent; }
    return (output_exponent << 23) | (significand & 0x7FFFFFu);
}
static inline void x_rsqrtps(float *destination, const float *source)
{
    uint32_t bits[4]; memcpy(bits, source, sizeof bits);
    for (unsigned lane = 0; lane < 4; ++lane) bits[lane] = x_rsqrt_bits(bits[lane]);
    memcpy(destination, bits, sizeof bits);
}


/* ---- MMX ------------------------------------------------------------------------------ */
static inline int32_t x_sat8(int32_t v)  { return v < -128 ? -128 : v > 127 ? 127 : v; }
static inline int32_t x_sat16(int32_t v) { return v < -32768 ? -32768 : v > 32767 ? 32767 : v; }
static inline uint32_t x_usat8(int32_t v)  { return v < 0 ? 0 : v > 255 ? 255 : (uint32_t)v; }
static inline uint32_t x_usat16(int32_t v) { return v < 0 ? 0 : v > 65535 ? 65535 : (uint32_t)v; }
#define X_MMX_LANES(name, N, LT, ST, EXPR)                                                             \
static inline uint64_t x_mmx_##name(uint64_t a, uint64_t b) {                                          \
    uint64_t r = 0; const unsigned W = 64 / (N); const uint64_t M = (N) == 1 ? ~0ull : ((1ull << W) - 1);  \
    for (unsigned i = 0; i < (N); ++i) { LT x = (LT)((a >> (i * W)) & M), y = (LT)((b >> (i * W)) & M);   \
        ST sx = (ST)x, sy = (ST)y; (void)sx; (void)sy; uint64_t z = (uint64_t)(EXPR) & M; r |= z << (i * W); } \
    return r; }
X_MMX_LANES(paddb, 8, uint8_t, int8_t, x + y)      X_MMX_LANES(paddw, 4, uint16_t, int16_t, x + y)      X_MMX_LANES(paddd, 2, uint32_t, int32_t, x + y)
X_MMX_LANES(psubb, 8, uint8_t, int8_t, x - y)      X_MMX_LANES(psubw, 4, uint16_t, int16_t, x - y)      X_MMX_LANES(psubd, 2, uint32_t, int32_t, x - y)
X_MMX_LANES(paddsb, 8, uint8_t, int8_t, (uint8_t)x_sat8(sx + sy))     X_MMX_LANES(paddsw, 4, uint16_t, int16_t, (uint16_t)x_sat16(sx + sy))
X_MMX_LANES(psubsb, 8, uint8_t, int8_t, (uint8_t)x_sat8(sx - sy))     X_MMX_LANES(psubsw, 4, uint16_t, int16_t, (uint16_t)x_sat16(sx - sy))
X_MMX_LANES(paddusb, 8, uint8_t, int8_t, x_usat8((int32_t)x + y))     X_MMX_LANES(paddusw, 4, uint16_t, int16_t, x_usat16((int32_t)x + y))
X_MMX_LANES(psubusb, 8, uint8_t, int8_t, x > y ? x - y : 0)           X_MMX_LANES(psubusw, 4, uint16_t, int16_t, x > y ? x - y : 0)
X_MMX_LANES(pmullw, 4, uint16_t, int16_t, (uint16_t)(sx * sy))        X_MMX_LANES(pmulhw, 4, uint16_t, int16_t, (uint16_t)(((int32_t)sx * sy) >> 16))
X_MMX_LANES(pmulhuw, 4, uint16_t, int16_t, (uint16_t)(((uint32_t)x * y) >> 16))
X_MMX_LANES(pcmpeqb, 8, uint8_t, int8_t, x == y ? 0xFF : 0)  X_MMX_LANES(pcmpeqw, 4, uint16_t, int16_t, x == y ? 0xFFFF : 0)  X_MMX_LANES(pcmpeqd, 2, uint32_t, int32_t, x == y ? 0xFFFFFFFFu : 0)
X_MMX_LANES(pcmpgtb, 8, uint8_t, int8_t, sx > sy ? 0xFF : 0) X_MMX_LANES(pcmpgtw, 4, uint16_t, int16_t, sx > sy ? 0xFFFF : 0) X_MMX_LANES(pcmpgtd, 2, uint32_t, int32_t, sx > sy ? 0xFFFFFFFFu : 0)
X_MMX_LANES(pavgb, 8, uint8_t, int8_t, (x + y + 1) >> 1)     X_MMX_LANES(pavgw, 4, uint16_t, int16_t, (x + y + 1) >> 1)
X_MMX_LANES(pminub, 8, uint8_t, int8_t, x < y ? x : y)        X_MMX_LANES(pmaxub, 8, uint8_t, int8_t, x > y ? x : y)
X_MMX_LANES(pminsw, 4, uint16_t, int16_t, sx < sy ? x : y)    X_MMX_LANES(pmaxsw, 4, uint16_t, int16_t, sx > sy ? x : y)
static inline uint64_t x_mmx_pand(uint64_t a, uint64_t b)  { return a & b; }
static inline uint64_t x_mmx_pandn(uint64_t a, uint64_t b) { return ~a & b; }
static inline uint64_t x_mmx_por(uint64_t a, uint64_t b)   { return a | b; }
static inline uint64_t x_mmx_pxor(uint64_t a, uint64_t b)  { return a ^ b; }
static inline uint64_t x_mmx_pmaddwd(uint64_t a, uint64_t b) {
    uint64_t r = 0;
    for (unsigned i = 0; i < 2; ++i) {
        int32_t p0 = (int16_t)(a >> (i * 32)) * (int16_t)(b >> (i * 32));
        int32_t p1 = (int16_t)(a >> (i * 32 + 16)) * (int16_t)(b >> (i * 32 + 16));
        r |= (uint64_t)(uint32_t)(p0 + p1) << (i * 32);
    }
    return r; }
static inline uint64_t x_mmx_unpack(uint64_t a, uint64_t b, unsigned w, int high) {
    uint64_t r = 0; unsigned n = 32 / w; uint64_t m = (1ull << w) - 1; unsigned base = high ? 32 : 0;
    for (unsigned i = 0; i < n; ++i) {
        r |= ((a >> (base + i * w)) & m) << (2 * i * w);
        r |= ((b >> (base + i * w)) & m) << ((2 * i + 1) * w);
    }
    return r; }
static inline uint64_t x_mmx_punpcklbw(uint64_t a, uint64_t b) { return x_mmx_unpack(a, b, 8, 0); }
static inline uint64_t x_mmx_punpcklwd(uint64_t a, uint64_t b) { return x_mmx_unpack(a, b, 16, 0); }
static inline uint64_t x_mmx_punpckldq(uint64_t a, uint64_t b) { return x_mmx_unpack(a, b, 32, 0); }
static inline uint64_t x_mmx_punpckhbw(uint64_t a, uint64_t b) { return x_mmx_unpack(a, b, 8, 1); }
static inline uint64_t x_mmx_punpckhwd(uint64_t a, uint64_t b) { return x_mmx_unpack(a, b, 16, 1); }
static inline uint64_t x_mmx_punpckhdq(uint64_t a, uint64_t b) { return x_mmx_unpack(a, b, 32, 1); }
static inline uint64_t x_mmx_packsswb(uint64_t a, uint64_t b) { uint64_t r = 0;
    for (unsigned i = 0; i < 4; ++i) { r |= (uint64_t)(uint8_t)x_sat8((int16_t)(a >> (i * 16))) << (i * 8); r |= (uint64_t)(uint8_t)x_sat8((int16_t)(b >> (i * 16))) << (32 + i * 8); } return r; }
static inline uint64_t x_mmx_packuswb(uint64_t a, uint64_t b) { uint64_t r = 0;
    for (unsigned i = 0; i < 4; ++i) { r |= (uint64_t)x_usat8((int16_t)(a >> (i * 16))) << (i * 8); r |= (uint64_t)x_usat8((int16_t)(b >> (i * 16))) << (32 + i * 8); } return r; }
static inline uint64_t x_mmx_packssdw(uint64_t a, uint64_t b) { uint64_t r = 0;
    for (unsigned i = 0; i < 2; ++i) { r |= (uint64_t)(uint16_t)x_sat16((int32_t)(a >> (i * 32))) << (i * 16); r |= (uint64_t)(uint16_t)x_sat16((int32_t)(b >> (i * 32))) << (32 + i * 16); } return r; }
static inline uint64_t x_mmx_shift(uint64_t a, uint64_t cnt, unsigned w, int dir) {   /* dir: 0 left, 1 logical right, 2 arithmetic right */
    uint64_t r = 0; unsigned n = 64 / w; uint64_t m = w == 64 ? ~0ull : ((1ull << w) - 1);
    for (unsigned i = 0; i < n; ++i) {
        uint64_t x = (a >> (i * w)) & m, z;
        if (dir == 0)      z = cnt >= w ? 0 : (x << cnt) & m;
        else if (dir == 1) z = cnt >= w ? 0 : x >> cnt;
        else { int64_t sx = (int64_t)(x << (64 - w)) >> (64 - w); z = (uint64_t)(sx >> (cnt >= w ? w - 1 : cnt)) & m; }
        r |= z << (i * w);
    }
    return r; }
static inline uint64_t x_mmx_psllw(uint64_t a, uint64_t c) { return x_mmx_shift(a, c, 16, 0); }
static inline uint64_t x_mmx_pslld(uint64_t a, uint64_t c) { return x_mmx_shift(a, c, 32, 0); }
static inline uint64_t x_mmx_psllq(uint64_t a, uint64_t c) { return x_mmx_shift(a, c, 64, 0); }
static inline uint64_t x_mmx_psrlw(uint64_t a, uint64_t c) { return x_mmx_shift(a, c, 16, 1); }
static inline uint64_t x_mmx_psrld(uint64_t a, uint64_t c) { return x_mmx_shift(a, c, 32, 1); }
static inline uint64_t x_mmx_psrlq(uint64_t a, uint64_t c) { return x_mmx_shift(a, c, 64, 1); }
static inline uint64_t x_mmx_psraw(uint64_t a, uint64_t c) { return x_mmx_shift(a, c, 16, 2); }
static inline uint64_t x_mmx_psrad(uint64_t a, uint64_t c) { return x_mmx_shift(a, c, 32, 2); }

uint64_t x_rdtsc(void);                       /* runtime: monotonic cycle-ish counter */

/* ---- dispatch ----------------------------------------------------------------------- */
typedef void (*xv_fn_t)(xctx *c);
typedef struct { uint32_t eip; xv_fn_t fn; } xv_fn_entry_t;
extern const xv_fn_entry_t xv_fn_table[];
extern const unsigned xv_fn_table_count;
extern const uint32_t xv_entry_point;
void xv_call(xctx *c, uint32_t target);              /* indirect call/jump: look up and run */
xv_fn_t xv_lookup(uint32_t eip);

#ifdef __cplusplus
}
#endif
