/* Generated by gen_layouts.py from halo_shaders.json - do not edit. */
#pragma once
#include "xv_shader.h"

static const xv_attr_desc_t xv_attrs_halo_vs_00[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "texcoord0", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 4, 9 },  /* v9 D3DCOLOR */
};
static const xv_vs_desc_t xv_vs_halo_vs_00 = {
    "app0:shaders/halo_vs_00.gxp", 1, { 16, 0, 0, 0 },
    2, xv_attrs_halo_vs_00, -96, 4, 0x001E1468u, 0x001E1388u, 0x978892BAu, 116u
};

static const xv_attr_desc_t xv_attrs_halo_vs_01[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "color1", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "texcoord0", XV_CONST_STREAM, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 4, 9 },  /* v9 constant-fed (SetVertexData4f) */
};
static const xv_vs_desc_t xv_vs_halo_vs_01 = {
    "app0:shaders/halo_vs_01.gxp", 1, { 16, 0, 0, 0 },
    3, xv_attrs_halo_vs_01, -96, 12, 0x001E14E0u, 0x001E1398u, 0xF8A4AE90u, 196u
};

static const xv_attr_desc_t xv_attrs_halo_vs_02[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "color1", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "texcoord0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 4, 9 },  /* v9 D3DCOLOR */
};
static const xv_vs_desc_t xv_vs_halo_vs_02 = {
    "app0:shaders/halo_vs_02.gxp", 1, { 24, 0, 0, 0 },
    3, xv_attrs_halo_vs_02, -96, 187, 0x001E15A8u, 0x001E13BCu, 0xC6657A43u, 452u
};

static const xv_attr_desc_t xv_attrs_halo_vs_03[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 0 },  /* v0 FLOAT2 */
    { "color1", 0, 8, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "texcoord0", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 4, 9 },  /* v9 D3DCOLOR */
};
static const xv_vs_desc_t xv_vs_halo_vs_03 = {
    "app0:shaders/halo_vs_03.gxp", 1, { 20, 0, 0, 0 },
    3, xv_attrs_halo_vs_03, -68, 11, 0x001E1770u, 0x001E13ECu, 0x1DAF0284u, 356u
};

static const xv_attr_desc_t xv_attrs_halo_vs_04[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 0 },  /* v0 FLOAT2 */
    { "color1", 0, 8, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "texcoord0", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 4, 9 },  /* v9 D3DCOLOR */
};
static const xv_vs_desc_t xv_vs_halo_vs_04 = {
    "app0:shaders/halo_vs_04.gxp", 1, { 20, 0, 0, 0 },
    3, xv_attrs_halo_vs_04, -68, 5, 0x001E18D8u, 0x001E13ECu, 0x4469E1F8u, 132u
};

static const xv_attr_desc_t xv_attrs_halo_vs_05[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_05 = {
    "app0:shaders/halo_vs_05.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_05, -96, 192, 0x001E1960u, 0x001E1400u, 0x8144CA76u, 372u
};

static const xv_attr_desc_t xv_attrs_halo_vs_06[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_06 = {
    "app0:shaders/halo_vs_06.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_06, -96, 11, 0x001E1AD8u, 0x001E144Cu, 0x3068A44Bu, 148u
};

static const xv_attr_desc_t xv_attrs_halo_vs_07[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "backcolor0", XV_CONST_STREAM, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 4, 7 },  /* v7 constant-fed (SetVertexData4f) */
};
static const xv_vs_desc_t xv_vs_halo_vs_07 = {
    "app0:shaders/halo_vs_07.gxp", 1, { 32, 0, 0, 0 },
    6, xv_attrs_halo_vs_07, -96, 6, 0x001E1B70u, 0x001E144Cu, 0x442D7BEAu, 388u
};

static const xv_attr_desc_t xv_attrs_halo_vs_08[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_08 = {
    "app0:shaders/halo_vs_08.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_08, -96, 13, 0x001E1CF8u, 0x001E144Cu, 0x8E8F42CEu, 132u
};

static const xv_attr_desc_t xv_attrs_halo_vs_09[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_09 = {
    "app0:shaders/halo_vs_09.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_09, -96, 192, 0x001E1D80u, 0x001E1400u, 0x9E2E9021u, 724u
};

static const xv_attr_desc_t xv_attrs_halo_vs_10[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_10 = {
    "app0:shaders/halo_vs_10.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_10, -96, 192, 0x001E2058u, 0x001E1400u, 0x393556F8u, 1060u
};

static const xv_attr_desc_t xv_attrs_halo_vs_11[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 3, 0 },  /* v0 PBYTE3 */
    { "texcoord0", 0, 3, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 3, 9 },  /* v9 PBYTE3 */
    { "backcolor1", 0, 6, SCE_GXM_ATTRIBUTE_FORMAT_S16, 1, 8 },  /* v8 S32Kx1 */
    { "normal", XV_CONST_STREAM, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 4, 2 },  /* v2 constant-fed (SetVertexData4f) */
    { "color0", XV_CONST_STREAM, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 4, 3 },  /* v3 constant-fed (SetVertexData4f) */
};
static const xv_vs_desc_t xv_vs_halo_vs_11 = {
    "app0:shaders/halo_vs_11.gxp", 1, { 8, 0, 0, 0 },
    5, xv_attrs_halo_vs_11, -96, 192, 0x001E2480u, 0x001E13A8u, 0x1405EB74u, 500u
};

static const xv_attr_desc_t xv_attrs_halo_vs_12[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "color1", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "texcoord0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 4, 9 },  /* v9 D3DCOLOR */
};
static const xv_vs_desc_t xv_vs_halo_vs_12 = {
    "app0:shaders/halo_vs_12.gxp", 1, { 24, 0, 0, 0 },
    3, xv_attrs_halo_vs_12, -96, 187, 0x001E2678u, 0x001E13BCu, 0xDB4E520Au, 468u
};

static const xv_attr_desc_t xv_attrs_halo_vs_13[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_13 = {
    "app0:shaders/halo_vs_13.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_13, -96, 192, 0x001E2850u, 0x001E1400u, 0x166818F8u, 340u
};

static const xv_attr_desc_t xv_attrs_halo_vs_14[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_14 = {
    "app0:shaders/halo_vs_14.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_14, -96, 192, 0x001E29A8u, 0x001E1400u, 0xC79F61EEu, 708u
};

static const xv_attr_desc_t xv_attrs_halo_vs_15[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_15 = {
    "app0:shaders/halo_vs_15.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_15, -96, 192, 0x001E2C70u, 0x001E1400u, 0x42F44E53u, 868u
};

static const xv_attr_desc_t xv_attrs_halo_vs_16[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "backcolor0", 1, 0, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 7 },  /* v7 NORMPACKED3 */
    { "backcolor1", 1, 4, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 8 },  /* v8 NORMSHORT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_16 = {
    "app0:shaders/halo_vs_16.gxp", 2, { 32, 8, 0, 0 },
    7, xv_attrs_halo_vs_16, -96, 19, 0x001E2FD8u, 0x001E1424u, 0x6150B892u, 404u
};

static const xv_attr_desc_t xv_attrs_halo_vs_17[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_17 = {
    "app0:shaders/halo_vs_17.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_17, -96, 192, 0x001E3170u, 0x001E1400u, 0x4A1C21F2u, 1268u
};

static const xv_attr_desc_t xv_attrs_halo_vs_18[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_18 = {
    "app0:shaders/halo_vs_18.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_18, -96, 192, 0x001E3668u, 0x001E1400u, 0xE877C70Fu, 628u
};

static const xv_attr_desc_t xv_attrs_halo_vs_19[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_19 = {
    "app0:shaders/halo_vs_19.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_19, -96, 23, 0x001E38E0u, 0x001E144Cu, 0xDE6968BDu, 660u
};

static const xv_attr_desc_t xv_attrs_halo_vs_20[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_20 = {
    "app0:shaders/halo_vs_20.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_20, -96, 9, 0x001E3B78u, 0x001E144Cu, 0xE09FEF67u, 196u
};

static const xv_attr_desc_t xv_attrs_halo_vs_21[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_21 = {
    "app0:shaders/halo_vs_21.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_21, -96, 16, 0x001E3C40u, 0x001E144Cu, 0x7F28B12Fu, 308u
};

static const xv_attr_desc_t xv_attrs_halo_vs_22[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_22 = {
    "app0:shaders/halo_vs_22.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_22, -96, 12, 0x001E3D78u, 0x001E144Cu, 0x3019A691u, 388u
};

static const xv_attr_desc_t xv_attrs_halo_vs_23[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_23 = {
    "app0:shaders/halo_vs_23.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_23, -96, 13, 0x001E3F00u, 0x001E144Cu, 0x50944328u, 340u
};

static const xv_attr_desc_t xv_attrs_halo_vs_24[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_24 = {
    "app0:shaders/halo_vs_24.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_24, -96, 23, 0x001E4058u, 0x001E144Cu, 0x9E6F8B13u, 596u
};

static const xv_attr_desc_t xv_attrs_halo_vs_25[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "backcolor0", 1, 0, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 7 },  /* v7 NORMPACKED3 */
    { "backcolor1", 1, 4, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 8 },  /* v8 NORMSHORT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_25 = {
    "app0:shaders/halo_vs_25.gxp", 2, { 32, 8, 0, 0 },
    7, xv_attrs_halo_vs_25, -96, 28, 0x001E42B0u, 0x001E1424u, 0x8A1EAB4Du, 884u
};

static const xv_attr_desc_t xv_attrs_halo_vs_26[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_26 = {
    "app0:shaders/halo_vs_26.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_26, -96, 15, 0x001E4628u, 0x001E144Cu, 0x39DC538Du, 324u
};

static const xv_attr_desc_t xv_attrs_halo_vs_27[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_27 = {
    "app0:shaders/halo_vs_27.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_27, -96, 63, 0x001E4770u, 0x001E1400u, 0x109DB448u, 388u
};

static const xv_attr_desc_t xv_attrs_halo_vs_28[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_28 = {
    "app0:shaders/halo_vs_28.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_28, -96, 13, 0x001E48F8u, 0x001E144Cu, 0xEEB6D0A9u, 548u
};

static const xv_attr_desc_t xv_attrs_halo_vs_29[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_29 = {
    "app0:shaders/halo_vs_29.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_29, -96, 20, 0x001E4B20u, 0x001E144Cu, 0xF0F51170u, 180u
};

static const xv_attr_desc_t xv_attrs_halo_vs_30[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_30 = {
    "app0:shaders/halo_vs_30.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_30, -96, 192, 0x001E4BD8u, 0x001E1400u, 0x2725AD9Au, 596u
};

static const xv_attr_desc_t xv_attrs_halo_vs_31[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_31 = {
    "app0:shaders/halo_vs_31.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_31, -96, 192, 0x001E4E30u, 0x001E1400u, 0xE5CA6845u, 1380u
};

static const xv_attr_desc_t xv_attrs_halo_vs_32[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_32 = {
    "app0:shaders/halo_vs_32.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_32, -96, 192, 0x001E5398u, 0x001E1400u, 0x5F294309u, 612u
};

static const xv_attr_desc_t xv_attrs_halo_vs_33[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 3, 0 },  /* v0 PBYTE3 */
    { "texcoord0", 0, 3, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 3, 9 },  /* v9 PBYTE3 */
    { "backcolor1", 0, 6, SCE_GXM_ATTRIBUTE_FORMAT_S16, 1, 8 },  /* v8 S32Kx1 */
    { "normal", XV_CONST_STREAM, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 4, 2 },  /* v2 constant-fed (SetVertexData4f) */
    { "color0", XV_CONST_STREAM, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 4, 3 },  /* v3 constant-fed (SetVertexData4f) */
    { "color1", XV_CONST_STREAM, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 4, 4 },  /* v4 constant-fed (SetVertexData4f) */
};
static const xv_vs_desc_t xv_vs_halo_vs_33 = {
    "app0:shaders/halo_vs_33.gxp", 1, { 8, 0, 0, 0 },
    6, xv_attrs_halo_vs_33, -96, 192, 0x001E5600u, 0x001E13A8u, 0xCA01577Bu, 484u
};

static const xv_attr_desc_t xv_attrs_halo_vs_34[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_34 = {
    "app0:shaders/halo_vs_34.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_34, -96, 23, 0x001E57E8u, 0x001E144Cu, 0x20DF9066u, 724u
};

static const xv_attr_desc_t xv_attrs_halo_vs_35[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_35 = {
    "app0:shaders/halo_vs_35.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_35, -96, 23, 0x001E5AC0u, 0x001E144Cu, 0x339F58D9u, 676u
};

static const xv_attr_desc_t xv_attrs_halo_vs_36[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_36 = {
    "app0:shaders/halo_vs_36.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_36, -96, 192, 0x001E5D68u, 0x001E1400u, 0x667FA8CAu, 948u
};

static const xv_attr_desc_t xv_attrs_halo_vs_37[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_37 = {
    "app0:shaders/halo_vs_37.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_37, -96, 6, 0x001E6120u, 0x001E144Cu, 0x9D682413u, 228u
};

static const xv_attr_desc_t xv_attrs_halo_vs_38[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 0 },  /* v0 FLOAT2 */
    { "color1", 0, 8, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "texcoord0", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 4, 9 },  /* v9 D3DCOLOR */
};
static const xv_vs_desc_t xv_vs_halo_vs_38 = {
    "app0:shaders/halo_vs_38.gxp", 1, { 20, 0, 0, 0 },
    3, xv_attrs_halo_vs_38, -81, 8, 0x001E6208u, 0x001E13ECu, 0xBB2F446Bu, 180u
};

static const xv_attr_desc_t xv_attrs_halo_vs_39[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_39 = {
    "app0:shaders/halo_vs_39.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_39, -89, 185, 0x001E62C0u, 0x001E1400u, 0x71412768u, 340u
};

static const xv_attr_desc_t xv_attrs_halo_vs_40[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_40 = {
    "app0:shaders/halo_vs_40.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_40, -96, 15, 0x001E6418u, 0x001E144Cu, 0xBC1EFF25u, 212u
};

static const xv_attr_desc_t xv_attrs_halo_vs_41[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_41 = {
    "app0:shaders/halo_vs_41.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_41, -96, 20, 0x001E64F0u, 0x001E144Cu, 0xD9FFD145u, 340u
};

static const xv_attr_desc_t xv_attrs_halo_vs_42[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_42 = {
    "app0:shaders/halo_vs_42.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_42, -96, 15, 0x001E6648u, 0x001E144Cu, 0x21E706ACu, 260u
};

static const xv_attr_desc_t xv_attrs_halo_vs_43[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_43 = {
    "app0:shaders/halo_vs_43.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_43, -96, 13, 0x001E6750u, 0x001E144Cu, 0xFA91064Du, 500u
};

static const xv_attr_desc_t xv_attrs_halo_vs_44[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "backcolor0", 1, 0, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 7 },  /* v7 NORMPACKED3 */
    { "backcolor1", 1, 4, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 8 },  /* v8 NORMSHORT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_44 = {
    "app0:shaders/halo_vs_44.gxp", 2, { 32, 8, 0, 0 },
    7, xv_attrs_halo_vs_44, -96, 15, 0x001E6948u, 0x001E1424u, 0xB1C59E95u, 356u
};

static const xv_attr_desc_t xv_attrs_halo_vs_45[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_45 = {
    "app0:shaders/halo_vs_45.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_45, -96, 192, 0x001E6AB0u, 0x001E1400u, 0x842ABBFAu, 948u
};

static const xv_attr_desc_t xv_attrs_halo_vs_46[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_46 = {
    "app0:shaders/halo_vs_46.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_46, -96, 13, 0x001E6E68u, 0x001E144Cu, 0xDE505E28u, 388u
};

static const xv_attr_desc_t xv_attrs_halo_vs_47[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_47 = {
    "app0:shaders/halo_vs_47.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_47, -96, 192, 0x001E6FF0u, 0x001E1400u, 0xAC1984DBu, 884u
};

static const xv_attr_desc_t xv_attrs_halo_vs_48[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_48 = {
    "app0:shaders/halo_vs_48.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_48, -96, 23, 0x001E7368u, 0x001E144Cu, 0xC8A57863u, 596u
};

static const xv_attr_desc_t xv_attrs_halo_vs_49[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_49 = {
    "app0:shaders/halo_vs_49.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_49, -96, 19, 0x001E75C0u, 0x001E144Cu, 0xE6B0E103u, 292u
};

static const xv_attr_desc_t xv_attrs_halo_vs_50[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_50 = {
    "app0:shaders/halo_vs_50.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_50, -96, 192, 0x001E76E8u, 0x001E1400u, 0x980F42ADu, 1156u
};

static const xv_attr_desc_t xv_attrs_halo_vs_51[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_51 = {
    "app0:shaders/halo_vs_51.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_51, -96, 15, 0x001E7B70u, 0x001E144Cu, 0x1B43D06Cu, 292u
};

static const xv_attr_desc_t xv_attrs_halo_vs_52[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "backcolor0", XV_CONST_STREAM, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 4, 7 },  /* v7 constant-fed (SetVertexData4f) */
};
static const xv_vs_desc_t xv_vs_halo_vs_52 = {
    "app0:shaders/halo_vs_52.gxp", 1, { 32, 0, 0, 0 },
    6, xv_attrs_halo_vs_52, -96, 8, 0x001E7C98u, 0x001E144Cu, 0x04E5022Au, 260u
};

static const xv_attr_desc_t xv_attrs_halo_vs_53[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_53 = {
    "app0:shaders/halo_vs_53.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_53, -96, 8, 0x001E7DA0u, 0x001E144Cu, 0xFB67EE5Cu, 260u
};

static const xv_attr_desc_t xv_attrs_halo_vs_54[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "backcolor0", XV_CONST_STREAM, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 4, 7 },  /* v7 constant-fed (SetVertexData4f) */
};
static const xv_vs_desc_t xv_vs_halo_vs_54 = {
    "app0:shaders/halo_vs_54.gxp", 1, { 32, 0, 0, 0 },
    6, xv_attrs_halo_vs_54, -96, 8, 0x001E7EA8u, 0x001E144Cu, 0x7DBE1693u, 564u
};

static const xv_attr_desc_t xv_attrs_halo_vs_55[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "backcolor0", XV_CONST_STREAM, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 4, 7 },  /* v7 constant-fed (SetVertexData4f) */
};
static const xv_vs_desc_t xv_vs_halo_vs_55 = {
    "app0:shaders/halo_vs_55.gxp", 1, { 32, 0, 0, 0 },
    6, xv_attrs_halo_vs_55, -96, 13, 0x001E80E0u, 0x001E144Cu, 0xD0D754FAu, 340u
};

static const xv_attr_desc_t xv_attrs_halo_vs_56[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "color1", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "texcoord0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 4, 9 },  /* v9 D3DCOLOR */
    { "texcoord1", XV_CONST_STREAM, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 4, 10 },  /* v10 constant-fed (SetVertexData4f) */
};
static const xv_vs_desc_t xv_vs_halo_vs_56 = {
    "app0:shaders/halo_vs_56.gxp", 1, { 24, 0, 0, 0 },
    4, xv_attrs_halo_vs_56, -68, 4, 0x001E8238u, 0x001E13BCu, 0x405809D3u, 148u
};

static const xv_attr_desc_t xv_attrs_halo_vs_57[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_57 = {
    "app0:shaders/halo_vs_57.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_57, -96, 192, 0x001E82D0u, 0x001E1400u, 0xFF7E5030u, 1012u
};

static const xv_attr_desc_t xv_attrs_halo_vs_58[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "backcolor0", 1, 0, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 7 },  /* v7 NORMPACKED3 */
    { "backcolor1", 1, 4, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 8 },  /* v8 NORMSHORT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_58 = {
    "app0:shaders/halo_vs_58.gxp", 2, { 32, 8, 0, 0 },
    7, xv_attrs_halo_vs_58, -96, 4, 0x001E86C8u, 0x001E1424u, 0x53C00F6Cu, 116u
};

static const xv_attr_desc_t xv_attrs_halo_vs_59[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "backcolor0", 1, 0, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 7 },  /* v7 NORMPACKED3 */
    { "backcolor1", 1, 4, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 8 },  /* v8 NORMSHORT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_59 = {
    "app0:shaders/halo_vs_59.gxp", 2, { 32, 8, 0, 0 },
    7, xv_attrs_halo_vs_59, -96, 15, 0x001E8740u, 0x001E1424u, 0x3DEBD366u, 308u
};

static const xv_attr_desc_t xv_attrs_halo_vs_60[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_60 = {
    "app0:shaders/halo_vs_60.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_60, -96, 192, 0x001E8878u, 0x001E1400u, 0x909ED3C4u, 884u
};

static const xv_attr_desc_t xv_attrs_halo_vs_61[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_61 = {
    "app0:shaders/halo_vs_61.gxp", 1, { 32, 0, 0, 0 },
    5, xv_attrs_halo_vs_61, -96, 13, 0x001E8BF0u, 0x001E144Cu, 0xCE3F8FC6u, 484u
};

static const xv_attr_desc_t xv_attrs_halo_vs_62[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_62 = {
    "app0:shaders/halo_vs_62.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_62, -96, 192, 0x001E8DD8u, 0x001E1400u, 0xC1FB6D8Cu, 964u
};

static const xv_attr_desc_t xv_attrs_halo_vs_63[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_63 = {
    "app0:shaders/halo_vs_63.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_63, -96, 192, 0x001E91A0u, 0x001E1400u, 0xD51EA0F3u, 916u
};

static const xv_attr_desc_t xv_attrs_halo_vs_64[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 */
};
static const xv_vs_desc_t xv_vs_halo_vs_64 = {
    "app0:shaders/halo_vs_64.gxp", 1, { 32, 0, 0, 0 },
    7, xv_attrs_halo_vs_64, -96, 192, 0x001E9538u, 0x001E1400u, 0x55A41AA7u, 660u
};

static const xv_attr_desc_t xv_attrs_halo_vs_65[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "color1", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "texcoord0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 4, 9 },  /* v9 D3DCOLOR */
};
static const xv_vs_desc_t xv_vs_halo_vs_65 = {
    "app0:shaders/halo_vs_65.gxp", 1, { 24, 0, 0, 0 },
    3, xv_attrs_halo_vs_65, -96, 187, 0x001E97D0u, 0x001E13BCu, 0x0619B0D9u, 420u
};

static const xv_attr_desc_t xv_attrs_halo_vs_66[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "color1", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 4 },  /* v4 FLOAT2 */
    { "texcoord0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 4, 9 },  /* v9 D3DCOLOR */
    { "texcoord2", 1, 0, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 11 },  /* v11 PBYTE2 */
};
static const xv_vs_desc_t xv_vs_halo_vs_66 = {
    "app0:shaders/halo_vs_66.gxp", 2, { 24, 2, 0, 0 },
    4, xv_attrs_halo_vs_66, -96, 187, 0x001E9978u, 0x001E13D0u, 0xA862CB93u, 564u
};

#define XV_HALO_VS_COUNT 67
static const xv_vs_desc_t *const xv_halo_vs[XV_HALO_VS_COUNT] = {
    &xv_vs_halo_vs_00,
    &xv_vs_halo_vs_01,
    &xv_vs_halo_vs_02,
    &xv_vs_halo_vs_03,
    &xv_vs_halo_vs_04,
    &xv_vs_halo_vs_05,
    &xv_vs_halo_vs_06,
    &xv_vs_halo_vs_07,
    &xv_vs_halo_vs_08,
    &xv_vs_halo_vs_09,
    &xv_vs_halo_vs_10,
    &xv_vs_halo_vs_11,
    &xv_vs_halo_vs_12,
    &xv_vs_halo_vs_13,
    &xv_vs_halo_vs_14,
    &xv_vs_halo_vs_15,
    &xv_vs_halo_vs_16,
    &xv_vs_halo_vs_17,
    &xv_vs_halo_vs_18,
    &xv_vs_halo_vs_19,
    &xv_vs_halo_vs_20,
    &xv_vs_halo_vs_21,
    &xv_vs_halo_vs_22,
    &xv_vs_halo_vs_23,
    &xv_vs_halo_vs_24,
    &xv_vs_halo_vs_25,
    &xv_vs_halo_vs_26,
    &xv_vs_halo_vs_27,
    &xv_vs_halo_vs_28,
    &xv_vs_halo_vs_29,
    &xv_vs_halo_vs_30,
    &xv_vs_halo_vs_31,
    &xv_vs_halo_vs_32,
    &xv_vs_halo_vs_33,
    &xv_vs_halo_vs_34,
    &xv_vs_halo_vs_35,
    &xv_vs_halo_vs_36,
    &xv_vs_halo_vs_37,
    &xv_vs_halo_vs_38,
    &xv_vs_halo_vs_39,
    &xv_vs_halo_vs_40,
    &xv_vs_halo_vs_41,
    &xv_vs_halo_vs_42,
    &xv_vs_halo_vs_43,
    &xv_vs_halo_vs_44,
    &xv_vs_halo_vs_45,
    &xv_vs_halo_vs_46,
    &xv_vs_halo_vs_47,
    &xv_vs_halo_vs_48,
    &xv_vs_halo_vs_49,
    &xv_vs_halo_vs_50,
    &xv_vs_halo_vs_51,
    &xv_vs_halo_vs_52,
    &xv_vs_halo_vs_53,
    &xv_vs_halo_vs_54,
    &xv_vs_halo_vs_55,
    &xv_vs_halo_vs_56,
    &xv_vs_halo_vs_57,
    &xv_vs_halo_vs_58,
    &xv_vs_halo_vs_59,
    &xv_vs_halo_vs_60,
    &xv_vs_halo_vs_61,
    &xv_vs_halo_vs_62,
    &xv_vs_halo_vs_63,
    &xv_vs_halo_vs_64,
    &xv_vs_halo_vs_65,
    &xv_vs_halo_vs_66,
};

static const xv_attr_desc_t xv_attrs_ff_test[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "texcoord0", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 4, 9 },  /* v9 D3DCOLOR */
};
static const xv_vs_desc_t xv_vs_ff_test = {
    "app0:shaders/halo_shader_0.gxp", 1, { 16, 0, 0, 0 }, 2, xv_attrs_ff_test, 0, 9, 0u, 0x001E1388u, 0u, 0u
};

static const xv_attr_desc_t xv_attrs_clear[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* clip-space xyz */
    { "color0", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 4, 3 },  /* D3DCOLOR */
};
static const xv_vs_desc_t xv_vs_clear = {
    "app0:shaders/xv_clear.gxp", 1, { 16, 0, 0, 0 }, 2, xv_attrs_clear, 0, 0, 0u, 0x00000000u, 0u, 0u
};

static const xv_attr_desc_t xv_attrs_model[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "blendweight", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 1 },  /* v1 NORMPACKED3 normal */
    { "normal", 0, 16, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 2 },  /* v2 NORMPACKED3 binormal */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8, 4, 3 },  /* v3 NORMPACKED3 tangent */
    { "color1", 0, 24, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 2, 4 },  /* v4 NORMSHORT2 texcoord */
    { "fog", 0, 28, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 2, 5 },  /* v5 PBYTE2 node indices */
    { "psize", 0, 30, SCE_GXM_ATTRIBUTE_FORMAT_S16N, 1, 6 },  /* v6 NORMSHORT1 node weight */
};
static const xv_vs_desc_t xv_vs_model = {
    "app0:shaders/xv_model.gxp", 1, { 32, 0, 0, 0 }, 7, xv_attrs_model, 0, 6, 0u, 0x001E1400u, 0u, 0u
};

static const xv_attr_desc_t xv_attrs_test_tex[] = {
    { "position", 0, 0, SCE_GXM_ATTRIBUTE_FORMAT_F32, 3, 0 },  /* v0 FLOAT3 */
    { "texcoord0", 0, 12, SCE_GXM_ATTRIBUTE_FORMAT_F32, 2, 9 },  /* v9 FLOAT2 */
    { "color0", 0, 20, SCE_GXM_ATTRIBUTE_FORMAT_U8N, 4, 3 },  /* v3 D3DCOLOR */
};
static const xv_vs_desc_t xv_vs_test_tex = {
    "app0:shaders/xv_test_tex.gxp", 1, { 24, 0, 0, 0 }, 3, xv_attrs_test_tex, 0, 4, 0u, 0x00000000u, 0u, 0u
};

