/* generated by tools/ps_pipeline.py: (vertex program fnv, combiner hash) -> fragment program */
typedef struct { uint32_t vs_fnv, ps_hash; const char *gxp; uint8_t cube_mask; } xv_ps_entry_t;   /* cube_mask: stages sampled with samplerCUBE */
static const xv_ps_entry_t xv_ps_table[] = {
    { 0x0619B0D9u, 0x10A61725u, "app0:shaders/ps_10A61725_07.frag.gxp", 0x00 },   /* halo_vs_65 */
    { 0x0619B0D9u, 0x3C7A2114u, "app0:shaders/ps_3C7A2114_07.frag.gxp", 0x0C },   /* halo_vs_65 */
    { 0x0619B0D9u, 0x419BB7FEu, "app0:shaders/ps_419BB7FE_07.frag.gxp", 0x00 },   /* halo_vs_65 */
    { 0x0619B0D9u, 0x53F6925Fu, "app0:shaders/ps_53F6925F_07.frag.gxp", 0x0C },   /* halo_vs_65 */
    { 0x0619B0D9u, 0x827BB3FEu, "app0:shaders/ps_827BB3FE_07.frag.gxp", 0x00 },   /* halo_vs_65 */
    { 0x0619B0D9u, 0x94D68E5Fu, "app0:shaders/ps_94D68E5F_07.frag.gxp", 0x0C },   /* halo_vs_65 */
    { 0x0619B0D9u, 0xB4DF2037u, "app0:shaders/ps_B4DF2037_07.frag.gxp", 0x08 },   /* halo_vs_65 */
    { 0x0619B0D9u, 0xF5BF1C37u, "app0:shaders/ps_F5BF1C37_07.frag.gxp", 0x08 },   /* halo_vs_65 */
    { 0x109DB448u, 0x154066FDu, "app0:shaders/ps_154066FD_0D.frag.gxp", 0x08 },   /* halo_vs_27 */
    { 0x109DB448u, 0x8A57DA30u, "app0:shaders/ps_8A57DA30_0D.frag.gxp", 0x08 },   /* halo_vs_27 */
    { 0x109DB448u, 0xE9632F91u, "app0:shaders/ps_E9632F91_0D.frag.gxp", 0x08 },   /* halo_vs_27 */
    { 0x166818F8u, 0x066AE138u, "app0:shaders/ps_066AE138_04.frag.gxp", 0x0C },   /* halo_vs_13 */
    { 0x20DF9066u, 0x9D10DD99u, "app0:shaders/ps_9D10DD99_3F.frag.gxp", 0x0C },   /* halo_vs_34 */
    { 0x20DF9066u, 0x9D325A47u, "app0:shaders/ps_9D325A47_3F.frag.gxp", 0x0C },   /* halo_vs_34 */
    { 0x21E706ACu, 0xC351EE40u, "app0:shaders/ps_C351EE40_3C.frag.gxp", 0x08 },   /* halo_vs_42 */
    { 0x2725AD9Au, 0x223982F4u, "app0:shaders/ps_223982F4_05.frag.gxp", 0x00 },   /* halo_vs_30 */
    { 0x2725AD9Au, 0x34945D55u, "app0:shaders/ps_34945D55_05.frag.gxp", 0x0C },   /* halo_vs_30 */
    { 0x2725AD9Au, 0x957CEB2Du, "app0:shaders/ps_957CEB2D_05.frag.gxp", 0x08 },   /* halo_vs_30 */
    { 0x3068A44Bu, 0x04EB62ADu, "app0:shaders/ps_04EB62AD_0C.frag.gxp", 0x0C },   /* halo_vs_06 */
    { 0x393556F8u, 0x0A8A37A5u, "app0:shaders/ps_0A8A37A5_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0x154066FDu, "app0:shaders/ps_154066FD_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0x1667DAC2u, "app0:shaders/ps_1667DAC2_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0x1955B8E9u, "app0:shaders/ps_1955B8E9_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0x5B6A2F85u, "app0:shaders/ps_5B6A2F85_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0x66089289u, "app0:shaders/ps_66089289_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0x709A7A05u, "app0:shaders/ps_709A7A05_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0x713BC366u, "app0:shaders/ps_713BC366_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0x8A57DA30u, "app0:shaders/ps_8A57DA30_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0x9416BE1Cu, "app0:shaders/ps_9416BE1C_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0xB5691565u, "app0:shaders/ps_B5691565_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0xC1B115A1u, "app0:shaders/ps_C1B115A1_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0xD8AABA3Au, "app0:shaders/ps_D8AABA3A_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0xF7761878u, "app0:shaders/ps_F7761878_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x393556F8u, 0xFD65DF94u, "app0:shaders/ps_FD65DF94_3F.frag.gxp", 0x08 },   /* halo_vs_10 */
    { 0x39DC538Du, 0x83314C96u, "app0:shaders/ps_83314C96_3C.frag.gxp", 0x08 },   /* halo_vs_26 */
    { 0x4A1C21F2u, 0x154066FDu, "app0:shaders/ps_154066FD_3F.frag.gxp", 0x08 },   /* halo_vs_17 */
    { 0x4A1C21F2u, 0x1955B8E9u, "app0:shaders/ps_1955B8E9_3F.frag.gxp", 0x08 },   /* halo_vs_17 */
    { 0x4A1C21F2u, 0x5B6A2F85u, "app0:shaders/ps_5B6A2F85_3F.frag.gxp", 0x08 },   /* halo_vs_17 */
    { 0x50944328u, 0x808A51ECu, "app0:shaders/ps_808A51EC_7C.frag.gxp", 0x0C },   /* halo_vs_23 */
    { 0x53C00F6Cu, 0x7E1DE228u, "app0:shaders/ps_7E1DE228_04.frag.gxp", 0x0C },   /* halo_vs_58 */
    { 0x5F294309u, 0x350C5B78u, "app0:shaders/ps_350C5B78_05.frag.gxp", 0x08 },   /* halo_vs_32 */
    { 0x5F294309u, 0x95F4E950u, "app0:shaders/ps_95F4E950_05.frag.gxp", 0x0C },   /* halo_vs_32 */
    { 0x5F294309u, 0xA84FC3B1u, "app0:shaders/ps_A84FC3B1_05.frag.gxp", 0x00 },   /* halo_vs_32 */
    { 0x6150B892u, 0x558BF0EFu, "app0:shaders/ps_558BF0EF_3D.frag.gxp", 0x00 },   /* halo_vs_16 */
    { 0x6150B892u, 0x953BD9C7u, "app0:shaders/ps_953BD9C7_3D.frag.gxp", 0x00 },   /* halo_vs_16 */
    { 0x6150B892u, 0xB6747EC7u, "app0:shaders/ps_B6747EC7_3D.frag.gxp", 0x04 },   /* halo_vs_16 */
    { 0x6150B892u, 0xD3BFAB36u, "app0:shaders/ps_D3BFAB36_3D.frag.gxp", 0x00 },   /* halo_vs_16 */
    { 0x667FA8CAu, 0x38967EBCu, "app0:shaders/ps_38967EBC_3D.frag.gxp", 0x08 },   /* halo_vs_36 */
    { 0x667FA8CAu, 0x4AF1591Du, "app0:shaders/ps_4AF1591D_3D.frag.gxp", 0x00 },   /* halo_vs_36 */
    { 0x667FA8CAu, 0xD7ADF0E4u, "app0:shaders/ps_D7ADF0E4_3D.frag.gxp", 0x08 },   /* halo_vs_36 */
    { 0x71412768u, 0x94AB5D88u, "app0:shaders/ps_94AB5D88_04.frag.gxp", 0x08 },   /* halo_vs_39 */
    { 0x7F28B12Fu, 0xF9700407u, "app0:shaders/ps_F9700407_3C.frag.gxp", 0x0C },   /* halo_vs_21 */
    { 0x909ED3C4u, 0x1C4305E1u, "app0:shaders/ps_1C4305E1_3F.frag.gxp", 0x0C },   /* halo_vs_60 */
    { 0x909ED3C4u, 0xCEF34D8Au, "app0:shaders/ps_CEF34D8A_3F.frag.gxp", 0x0C },   /* halo_vs_60 */
    { 0x980F42ADu, 0xDA3413FAu, "app0:shaders/ps_DA3413FA_0D.frag.gxp", 0x00 },   /* halo_vs_50 */
    { 0x980F42ADu, 0xEC8EEE5Bu, "app0:shaders/ps_EC8EEE5B_0D.frag.gxp", 0x0C },   /* halo_vs_50 */
    { 0x9E2E9021u, 0x0A8A37A5u, "app0:shaders/ps_0A8A37A5_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0x154066FDu, "app0:shaders/ps_154066FD_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0x1667DAC2u, "app0:shaders/ps_1667DAC2_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0x1955B8E9u, "app0:shaders/ps_1955B8E9_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0x5B6A2F85u, "app0:shaders/ps_5B6A2F85_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0x66089289u, "app0:shaders/ps_66089289_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0x709A7A05u, "app0:shaders/ps_709A7A05_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0x713BC366u, "app0:shaders/ps_713BC366_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0x8A57DA30u, "app0:shaders/ps_8A57DA30_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0x9416BE1Cu, "app0:shaders/ps_9416BE1C_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0xA504588Cu, "app0:shaders/ps_A504588C_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0xB5691565u, "app0:shaders/ps_B5691565_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0xC1B115A1u, "app0:shaders/ps_C1B115A1_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0xD8AABA3Au, "app0:shaders/ps_D8AABA3A_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E2E9021u, 0xF7761878u, "app0:shaders/ps_F7761878_7F.frag.gxp", 0x08 },   /* halo_vs_09 */
    { 0x9E6F8B13u, 0x04CD48C4u, "app0:shaders/ps_04CD48C4_3F.frag.gxp", 0x0C },   /* halo_vs_24 */
    { 0x9E6F8B13u, 0x3B610FDBu, "app0:shaders/ps_3B610FDB_3F.frag.gxp", 0x0C },   /* halo_vs_24 */
    { 0x9E6F8B13u, 0x4053FF24u, "app0:shaders/ps_4053FF24_3F.frag.gxp", 0x00 },   /* halo_vs_24 */
    { 0x9E6F8B13u, 0x52AED985u, "app0:shaders/ps_52AED985_3F.frag.gxp", 0x0C },   /* halo_vs_24 */
    { 0x9E6F8B13u, 0x8020FC1Du, "app0:shaders/ps_8020FC1D_3F.frag.gxp", 0x00 },   /* halo_vs_24 */
    { 0x9E6F8B13u, 0xBBAE240Fu, "app0:shaders/ps_BBAE240F_3F.frag.gxp", 0x0C },   /* halo_vs_24 */
    { 0xA862CB93u, 0x10A61725u, "app0:shaders/ps_10A61725_3F.frag.gxp", 0x00 },   /* halo_vs_66 */
    { 0xA862CB93u, 0x352D4EB6u, "app0:shaders/ps_352D4EB6_3F.frag.gxp", 0x0C },   /* halo_vs_66 */
    { 0xA862CB93u, 0x3C7A2114u, "app0:shaders/ps_3C7A2114_3F.frag.gxp", 0x0C },   /* halo_vs_66 */
    { 0xA862CB93u, 0x63A1A3AEu, "app0:shaders/ps_63A1A3AE_3F.frag.gxp", 0x08 },   /* halo_vs_66 */
    { 0xA862CB93u, 0x8DB79D9Du, "app0:shaders/ps_8DB79D9D_3F.frag.gxp", 0x0C },   /* halo_vs_66 */
    { 0xA862CB93u, 0xA144F7A7u, "app0:shaders/ps_A144F7A7_3F.frag.gxp", 0x00 },   /* halo_vs_66 */
    { 0xA862CB93u, 0xA4819FAEu, "app0:shaders/ps_A4819FAE_3F.frag.gxp", 0x08 },   /* halo_vs_66 */
    { 0xA862CB93u, 0xBF689A9Cu, "app0:shaders/ps_BF689A9C_3F.frag.gxp", 0x00 },   /* halo_vs_66 */
    { 0xA862CB93u, 0xE224F3A7u, "app0:shaders/ps_E224F3A7_3F.frag.gxp", 0x00 },   /* halo_vs_66 */
    { 0xA862CB93u, 0xF44D52B6u, "app0:shaders/ps_F44D52B6_3F.frag.gxp", 0x0C },   /* halo_vs_66 */
    { 0xAC1984DBu, 0x00A51E16u, "app0:shaders/ps_00A51E16_3F.frag.gxp", 0x08 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x00F0B53Bu, "app0:shaders/ps_00F0B53B_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x0142DC52u, "app0:shaders/ps_0142DC52_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x04CD48C4u, "app0:shaders/ps_04CD48C4_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x07438186u, "app0:shaders/ps_07438186_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x0D1D8AEDu, "app0:shaders/ps_0D1D8AED_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x1422652Eu, "app0:shaders/ps_1422652E_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x200B6850u, "app0:shaders/ps_200B6850_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x2510CF1Cu, "app0:shaders/ps_2510CF1C_3F.frag.gxp", 0x08 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x2A588971u, "app0:shaders/ps_2A588971_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x2A68B75Cu, "app0:shaders/ps_2A68B75C_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x2C667527u, "app0:shaders/ps_2C667527_3F.frag.gxp", 0x08 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x326642B1u, "app0:shaders/ps_326642B1_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x339322E9u, "app0:shaders/ps_339322E9_3F.frag.gxp", 0x08 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x37715CB6u, "app0:shaders/ps_37715CB6_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x38F194DCu, "app0:shaders/ps_38F194DC_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x4053FF24u, "app0:shaders/ps_4053FF24_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x4662F1D3u, "app0:shaders/ps_4662F1D3_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x49CC3717u, "app0:shaders/ps_49CC3717_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x52AED985u, "app0:shaders/ps_52AED985_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x54A57F0Cu, "app0:shaders/ps_54A57F0C_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x552EB502u, "app0:shaders/ps_552EB502_3F.frag.gxp", 0x08 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x58A1B97Cu, "app0:shaders/ps_58A1B97C_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x65B5D69Cu, "app0:shaders/ps_65B5D69C_3F.frag.gxp", 0x08 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x69A1D468u, "app0:shaders/ps_69A1D468_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x6AFC93DDu, "app0:shaders/ps_6AFC93DD_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x6E89EEF8u, "app0:shaders/ps_6E89EEF8_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x73E8864Fu, "app0:shaders/ps_73E8864F_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x750AF306u, "app0:shaders/ps_750AF306_3F.frag.gxp", 0x08 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x7985715Du, "app0:shaders/ps_7985715D_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x7F246F82u, "app0:shaders/ps_7F246F82_3F.frag.gxp", 0x08 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x8020FC1Du, "app0:shaders/ps_8020FC1D_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x8833CF56u, "app0:shaders/ps_8833CF56_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x890FC73Fu, "app0:shaders/ps_890FC73F_3F.frag.gxp", 0x08 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x98543755u, "app0:shaders/ps_98543755_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x9CBAA590u, "app0:shaders/ps_9CBAA590_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0x9FBC903Eu, "app0:shaders/ps_9FBC903E_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xA6DD14D5u, "app0:shaders/ps_A6DD14D5_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xAA3E75F8u, "app0:shaders/ps_AA3E75F8_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xB0ABB5E7u, "app0:shaders/ps_B0ABB5E7_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xB164FC27u, "app0:shaders/ps_B164FC27_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xB3324074u, "app0:shaders/ps_B3324074_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xB397675Du, "app0:shaders/ps_B397675D_3F.frag.gxp", 0x08 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xB4AB6D30u, "app0:shaders/ps_B4AB6D30_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xB7B7C872u, "app0:shaders/ps_B7B7C872_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xC4284144u, "app0:shaders/ps_C4284144_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xC9112A71u, "app0:shaders/ps_C9112A71_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xCC1D85B3u, "app0:shaders/ps_CC1D85B3_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xCEAD4477u, "app0:shaders/ps_CEAD4477_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xD688CEDEu, "app0:shaders/ps_D688CEDE_3F.frag.gxp", 0x08 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xDE7EC140u, "app0:shaders/ps_DE7EC140_3F.frag.gxp", 0x08 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xE00CFD5Au, "app0:shaders/ps_E00CFD5A_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xE84E5B3Fu, "app0:shaders/ps_E84E5B3F_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xE9F85517u, "app0:shaders/ps_E9F85517_3F.frag.gxp", 0x0C },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xF267D7BBu, "app0:shaders/ps_F267D7BB_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xF668CDE9u, "app0:shaders/ps_F668CDE9_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xF6D738BFu, "app0:shaders/ps_F6D738BF_3F.frag.gxp", 0x00 },   /* halo_vs_47 */
    { 0xAC1984DBu, 0xF7B92BA4u, "app0:shaders/ps_F7B92BA4_3F.frag.gxp", 0x08 },   /* halo_vs_47 */
    { 0xBC1EFF25u, 0x14AFDED5u, "app0:shaders/ps_14AFDED5_3C.frag.gxp", 0x08 },   /* halo_vs_40 */
    { 0xBC1EFF25u, 0x75986CADu, "app0:shaders/ps_75986CAD_3C.frag.gxp", 0x0C },   /* halo_vs_40 */
    { 0xBC1EFF25u, 0x973DBF58u, "app0:shaders/ps_973DBF58_3C.frag.gxp", 0x00 },   /* halo_vs_40 */
    { 0xBC1EFF25u, 0x9B0FBC39u, "app0:shaders/ps_9B0FBC39_3C.frag.gxp", 0x0C },   /* halo_vs_40 */
    { 0xBC1EFF25u, 0xAFF5541Cu, "app0:shaders/ps_AFF5541C_3C.frag.gxp", 0x00 },   /* halo_vs_40 */
    { 0xBC1EFF25u, 0xFBF84A11u, "app0:shaders/ps_FBF84A11_3C.frag.gxp", 0x08 },   /* halo_vs_40 */
    { 0xC6657A43u, 0xDE09AB76u, "app0:shaders/ps_DE09AB76_0F.frag.gxp", 0x0C },   /* halo_vs_02 */
    { 0xD9FFD145u, 0xD05FE9D0u, "app0:shaders/ps_D05FE9D0_7C.frag.gxp", 0x0E },   /* halo_vs_41 */
    { 0xDB4E520Au, 0xDE09AB76u, "app0:shaders/ps_DE09AB76_0F.frag.gxp", 0x0C },   /* halo_vs_12 */
    { 0xE09FEF67u, 0x0D1A33B0u, "app0:shaders/ps_0D1A33B0_4C.frag.gxp", 0x0C },   /* halo_vs_20 */
    { 0xE5CA6845u, 0x70B9F45Cu, "app0:shaders/ps_70B9F45C_3F.frag.gxp", 0x08 },   /* halo_vs_31 */
    { 0xE6B0E103u, 0x09297772u, "app0:shaders/ps_09297772_3C.frag.gxp", 0x08 },   /* halo_vs_49 */
    { 0xE6B0E103u, 0x6A12054Au, "app0:shaders/ps_6A12054A_3C.frag.gxp", 0x0C },   /* halo_vs_49 */
    { 0xF0F51170u, 0x039E1B72u, "app0:shaders/ps_039E1B72_0D.frag.gxp", 0x08 },   /* halo_vs_29 */
    { 0xF8A4AE90u, 0x0E9CC93Bu, "app0:shaders/ps_0E9CC93B_07.frag.gxp", 0x08 },   /* halo_vs_01 */
    { 0xF8A4AE90u, 0x18872093u, "app0:shaders/ps_18872093_07.frag.gxp", 0x08 },   /* halo_vs_01 */
    { 0xF8A4AE90u, 0x1DCA6A29u, "app0:shaders/ps_1DCA6A29_07.frag.gxp", 0x08 },   /* halo_vs_01 */
    { 0xF8A4AE90u, 0x266A5B3Bu, "app0:shaders/ps_266A5B3B_07.frag.gxp", 0x0C },   /* halo_vs_01 */
    { 0xF8A4AE90u, 0x432A56F1u, "app0:shaders/ps_432A56F1_07.frag.gxp", 0x0C },   /* halo_vs_01 */
    { 0xF8A4AE90u, 0x6F855713u, "app0:shaders/ps_6F855713_07.frag.gxp", 0x0C },   /* halo_vs_01 */
    { 0xF8A4AE90u, 0x76F54297u, "app0:shaders/ps_76F54297_07.frag.gxp", 0x08 },   /* halo_vs_01 */
    { 0xF8A4AE90u, 0x81F7AC99u, "app0:shaders/ps_81F7AC99_07.frag.gxp", 0x08 },   /* halo_vs_01 */
    { 0xF8A4AE90u, 0x8752E913u, "app0:shaders/ps_8752E913_07.frag.gxp", 0x08 },   /* halo_vs_01 */
    { 0xF8A4AE90u, 0xA4437715u, "app0:shaders/ps_A4437715_07.frag.gxp", 0x08 },   /* halo_vs_01 */
    { 0xF8A4AE90u, 0xDC0B9B43u, "app0:shaders/ps_DC0B9B43_07.frag.gxp", 0x08 },   /* halo_vs_01 */
    { 0xF8A4AE90u, 0xE241C919u, "app0:shaders/ps_E241C919_07.frag.gxp", 0x08 },   /* halo_vs_01 */
    { 0xF8A4AE90u, 0xE2E03A71u, "app0:shaders/ps_E2E03A71_07.frag.gxp", 0x0C },   /* halo_vs_01 */
    { 0xFF7E5030u, 0x3C49CC6Fu, "app0:shaders/ps_3C49CC6F_3F.frag.gxp", 0x08 },   /* halo_vs_57 */
    { 0xFF7E5030u, 0x47B54A9Eu, "app0:shaders/ps_47B54A9E_3F.frag.gxp", 0x08 },   /* halo_vs_57 */
    { 0xFF7E5030u, 0x79C502D9u, "app0:shaders/ps_79C502D9_3F.frag.gxp", 0x0C },   /* halo_vs_57 */
    { 0xFF7E5030u, 0x9D325A47u, "app0:shaders/ps_9D325A47_3F.frag.gxp", 0x0C },   /* halo_vs_57 */
    { 0xFF7E5030u, 0xA89DD876u, "app0:shaders/ps_A89DD876_3F.frag.gxp", 0x0C },   /* halo_vs_57 */
    { 0xFF7E5030u, 0xAC6FD557u, "app0:shaders/ps_AC6FD557_3F.frag.gxp", 0x00 },   /* halo_vs_57 */
    { 0xFF7E5030u, 0xBAF8B2D7u, "app0:shaders/ps_BAF8B2D7_3F.frag.gxp", 0x00 },   /* halo_vs_57 */
};
#define XV_PS_TABLE_COUNT (sizeof xv_ps_table / sizeof xv_ps_table[0])
typedef struct { uint32_t vs_fnv; uint8_t outputs; } xv_vs_out_t;
static const xv_vs_out_t xv_vs_outputs[] = {
    { 0x04E5022Au, 0x03 },   /* halo_vs_52: color0,color1 */
    { 0x0619B0D9u, 0x07 },   /* halo_vs_65: color0,color1,texcoord0 */
    { 0x109DB448u, 0x0D },   /* halo_vs_27: color0,texcoord0,texcoord1 */
    { 0x1405EB74u, 0x05 },   /* halo_vs_11: color0,texcoord0 */
    { 0x166818F8u, 0x04 },   /* halo_vs_13: texcoord0 */
    { 0x1B43D06Cu, 0x3C },   /* halo_vs_51: texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x1DAF0284u, 0x1D },   /* halo_vs_03: color0,texcoord0,texcoord1,texcoord2 */
    { 0x20DF9066u, 0x3F },   /* halo_vs_34: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x21E706ACu, 0x3C },   /* halo_vs_42: texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x2725AD9Au, 0x05 },   /* halo_vs_30: color0,texcoord0 */
    { 0x3019A691u, 0x05 },   /* halo_vs_22: color0,texcoord0 */
    { 0x3068A44Bu, 0x0C },   /* halo_vs_06: texcoord0,texcoord1 */
    { 0x339F58D9u, 0x3F },   /* halo_vs_35: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x393556F8u, 0x3F },   /* halo_vs_10: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x39DC538Du, 0x3C },   /* halo_vs_26: texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x3DEBD366u, 0x3C },   /* halo_vs_59: texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x405809D3u, 0x07 },   /* halo_vs_56: color0,color1,texcoord0 */
    { 0x42F44E53u, 0x0F },   /* halo_vs_15: color0,color1,texcoord0,texcoord1 */
    { 0x442D7BEAu, 0x3F },   /* halo_vs_07: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x4469E1F8u, 0x05 },   /* halo_vs_04: color0,texcoord0 */
    { 0x4A1C21F2u, 0x3F },   /* halo_vs_17: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x50944328u, 0x7C },   /* halo_vs_23: fog,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x53C00F6Cu, 0x04 },   /* halo_vs_58: texcoord0 */
    { 0x55A41AA7u, 0x1D },   /* halo_vs_64: color0,texcoord0,texcoord1,texcoord2 */
    { 0x5F294309u, 0x05 },   /* halo_vs_32: color0,texcoord0 */
    { 0x6150B892u, 0x3D },   /* halo_vs_16: color0,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x667FA8CAu, 0x3D },   /* halo_vs_36: color0,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x71412768u, 0x04 },   /* halo_vs_39: texcoord0 */
    { 0x7DBE1693u, 0x7F },   /* halo_vs_54: color0,color1,fog,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x7F28B12Fu, 0x3C },   /* halo_vs_21: texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x8144CA76u, 0x4C },   /* halo_vs_05: fog,texcoord0,texcoord1 */
    { 0x842ABBFAu, 0x3F },   /* halo_vs_45: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x8A1EAB4Du, 0x1D },   /* halo_vs_25: color0,texcoord0,texcoord1,texcoord2 */
    { 0x8E8F42CEu, 0x44 },   /* halo_vs_08: fog,texcoord0 */
    { 0x909ED3C4u, 0x3F },   /* halo_vs_60: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x978892BAu, 0x01 },   /* halo_vs_00: color0 */
    { 0x980F42ADu, 0x0D },   /* halo_vs_50: color0,texcoord0,texcoord1 */
    { 0x9D682413u, 0x3F },   /* halo_vs_37: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x9E2E9021u, 0x7F },   /* halo_vs_09: color0,color1,fog,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0x9E6F8B13u, 0x3F },   /* halo_vs_24: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xA862CB93u, 0x3F },   /* halo_vs_66: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xAC1984DBu, 0x3F },   /* halo_vs_47: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xB1C59E95u, 0x3C },   /* halo_vs_44: texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xBB2F446Bu, 0x3C },   /* halo_vs_38: texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xBC1EFF25u, 0x3C },   /* halo_vs_40: texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xC1FB6D8Cu, 0x3F },   /* halo_vs_62: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xC6657A43u, 0x0F },   /* halo_vs_02: color0,color1,texcoord0,texcoord1 */
    { 0xC79F61EEu, 0x7C },   /* halo_vs_14: fog,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xC8A57863u, 0x3F },   /* halo_vs_48: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xCA01577Bu, 0x05 },   /* halo_vs_33: color0,texcoord0 */
    { 0xCE3F8FC6u, 0x3D },   /* halo_vs_61: color0,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xD0D754FAu, 0x0F },   /* halo_vs_55: color0,color1,texcoord0,texcoord1 */
    { 0xD51EA0F3u, 0x3D },   /* halo_vs_63: color0,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xD9FFD145u, 0x7C },   /* halo_vs_41: fog,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xDB4E520Au, 0x0F },   /* halo_vs_12: color0,color1,texcoord0,texcoord1 */
    { 0xDE505E28u, 0x05 },   /* halo_vs_46: color0,texcoord0 */
    { 0xDE6968BDu, 0x3F },   /* halo_vs_19: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xE09FEF67u, 0x4C },   /* halo_vs_20: fog,texcoord0,texcoord1 */
    { 0xE5CA6845u, 0x3F },   /* halo_vs_31: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xE6B0E103u, 0x3C },   /* halo_vs_49: texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xE877C70Fu, 0x4C },   /* halo_vs_18: fog,texcoord0,texcoord1 */
    { 0xEEB6D0A9u, 0x3D },   /* halo_vs_28: color0,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xF0F51170u, 0x0D },   /* halo_vs_29: color0,texcoord0,texcoord1 */
    { 0xF8A4AE90u, 0x07 },   /* halo_vs_01: color0,color1,texcoord0 */
    { 0xFA91064Du, 0x3D },   /* halo_vs_43: color0,texcoord0,texcoord1,texcoord2,texcoord3 */
    { 0xFB67EE5Cu, 0x03 },   /* halo_vs_53: color0,color1 */
    { 0xFF7E5030u, 0x3F },   /* halo_vs_57: color0,color1,texcoord0,texcoord1,texcoord2,texcoord3 */
};
#define XV_VS_OUTPUTS_COUNT (sizeof xv_vs_outputs / sizeof xv_vs_outputs[0])
