#!/usr/bin/env python3
"""Embed the HUD programs so an executable-only USB update stays self-contained."""
from pathlib import Path
import sys

root = Path(__file__).resolve().parent.parent
target = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "shaders/xv_hud_gxp.h"
hashes = ("A972FE61", "5D70F0B3", "EB818129")
lines = ["/* Generated by tools/embed_hud_shaders.py; do not edit. */", "#pragma once", "#include <stdint.h>"]
for h in hashes:
    data = (root / f"shaders/ps_{h}_1D.frag.gxp").read_bytes()
    if data[:4] != b"GXP\0":
        raise SystemExit(f"Invalid GXP magic: {h}")
    lines.append(f"static const uint8_t xv_hud_{h}[] = {{")
    for start in range(0, len(data), 16):
        lines.append("    " + ",".join(f"0x{v:02x}" for v in data[start:start + 16]) + ",")
    lines.append("};")
lines += ["static const struct { const char *path; const uint8_t *data; unsigned size; } xv_hud_gxp[] = {"]
for h in hashes:
    lines.append(f'    {{"app0:shaders/ps_{h}_1D.frag.gxp", xv_hud_{h}, sizeof(xv_hud_{h})}},')
lines.append("};")
target.write_text("\n".join(lines) + "\n")
