#!/usr/bin/env python3
"""Embed the project's actual notice and GPL text for offline dashboard reading."""
from pathlib import Path
import argparse
import json
import textwrap

ROOT = Path(__file__).resolve().parents[1]


def generate(root=ROOT):
    notice = (root / 'NOTICE').read_text(encoding='utf-8')
    license_text = (root / 'LICENSE').read_text(encoding='utf-8')
    if 'Version 3, 29 June 2007' not in license_text:
        raise ValueError('Expected the full GPL version 3 license')
    lines = []
    for line in (notice + '\n' + license_text).splitlines():
        lines.extend(textwrap.wrap(line, width=84, replace_whitespace=False,
                                   drop_whitespace=True) or [''])
    body = '\n'.join('    ' + json.dumps(line, ensure_ascii=True) + ',' for line in lines)
    return ('/* Generated by tools/embed_license.py from NOTICE and LICENSE. */\n'
            '#ifndef XV_DASH_LICENSE_TEXT_H\n#define XV_DASH_LICENSE_TEXT_H\n'
            'static const char *const xv_license_lines[] = {\n' + body +
            '\n};\n#endif\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = ROOT / 'dashboard/license_text.h'
    expected = generate()
    if args.check:
        if not output.exists() or output.read_text() != expected:
            raise SystemExit('Dashboard license text is out of date; run tools/embed_license.py')
    else:
        output.write_text(expected, encoding='utf-8')
