#!/usr/bin/env python3
"""Bundle table-referenced fragment programs for executable-only USB updates."""
from pathlib import Path
import re
import sys

root = Path(__file__).resolve().parents[1]
target = Path(sys.argv[1]) if len(sys.argv) > 1 else root / 'shaders/xv_ps_gxp.h'
paths = sorted(set(re.findall(r'"app0:(shaders/[^\"]+\.gxp)"',
                             (root / 'shaders/xv_ps_table.h').read_text())))
if not paths:
    raise SystemExit('No fragment programs in table')
variants = [p.replace('.frag.gxp', '_na.frag.gxp') for p in paths]
for path in variants:
    if not (root/path).is_file():
        raise SystemExit(f'Missing alpha-disabled shader: {path}; run specialize_ps_alpha.py and compile it')
variants += [p.replace('.frag.gxp', '_gt.frag.gxp') for p in paths if Path(p).name.startswith('ps_154066FD_')]
# Alpha-zero programs (tools/specialize_ps_alphazero.py) are optional: the runtime falls back to the discard program.
variants += [a for a in (p.replace('.frag.gxp', '_az.frag.gxp') for p in paths) if (root/a).is_file()]
# Guarded black-placeholder material variants are optional; missing programs
# retain the ordinary alpha-disabled path.
variants += [a for a in (p.replace(".frag.gxp", "_axisblack_na.frag.gxp") for p in paths) if (root/a).is_file()]
variants += [a for a in (p.replace(".frag.gxp", "_axisblack.frag.gxp") for p in paths) if (root/a).is_file()]
variants += [a for a in (p.replace(".frag.gxp", "_axisblack_gt.frag.gxp") for p in paths) if (root/a).is_file()]
variants += [a for a in (p.replace(".frag.gxp", "_axisblack_gt_cost.frag.gxp") for p in paths) if (root/a).is_file()]
# The draw recorder must know the samplers of every possible fallback too.
# Embed the same compiled programs that the package already ships, so an
# executable-only update and its preparation metadata cannot disagree.
fallbacks = [f'shaders/xv_{name}.frag.gxp' for name in ('color', 'texmod', 'tex0', 'lm')]
paths = sorted(set(paths + variants + fallbacks))
lines = ['/* Generated by tools/embed_ps_shaders.py; do not edit. */',
         '#pragma once', '#include <stdint.h>']
for i, path in enumerate(paths):
    data = (root / path).read_bytes()
    if data[:4] != b'GXP\0':
        raise SystemExit(f'Invalid GXP: {path}')
    lines.append(f'_Alignas(4) static const uint8_t xv_ps_bytes_{i}[] = {{')
    for pos in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{x:02x}' for x in data[pos:pos+24]) + ',')
    lines.append('};')
lines.append('static const struct { const char *path; const uint8_t *data; unsigned size; } xv_ps_embedded[] = {')
for i, path in enumerate(paths):
    lines.append(f'    {{"app0:{path}", xv_ps_bytes_{i}, sizeof xv_ps_bytes_{i}}},')
lines.append('};')
text = '\n'.join(lines) + '\n'
if not target.exists() or target.read_text() != text:
    target.write_text(text)
