#!/usr/bin/env python3
"""Embed layout-referenced vertex programs for executable-only USB updates."""
from pathlib import Path
import re, struct, sys
root = Path(__file__).resolve().parents[1]
target = Path(sys.argv[1]) if len(sys.argv) > 1 else root / 'shaders/xv_vs_gxp.h'
paths = sorted(set(re.findall(r'"app0:(shaders/[^"\n]+\.gxp)"',
                             (root / 'shaders/xv_layouts.h').read_text())))
if not paths:
    raise SystemExit('No vertex programs in layouts')
lines = ['/* Generated by tools/embed_vertex_shaders.py; do not edit. */',
         '#pragma once', '#include <stdint.h>']
for i, path in enumerate(paths):
    data = (root / path).read_bytes()
    if (len(data) < 0x30 or data[:4] != b'GXP\0'
            or not 0x30 <= struct.unpack_from('<I', data, 8)[0] <= len(data)
            or struct.unpack_from('<I', data, 0x14)[0] & 1):
        raise SystemExit(f'Invalid vertex GXP: {path}')
    lines.append(f'_Alignas(4) static const uint8_t xv_vs_bytes_{i}[] = {{')
    for pos in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{x:02x}' for x in data[pos:pos+24]) + ',')
    lines.append('};')
lines.append('static const struct { const char *path; const uint8_t *data; unsigned size; } xv_vs_embedded[] = {')
for i, path in enumerate(paths):
    lines.append(f'    {{"app0:{path}", xv_vs_bytes_{i}, sizeof xv_vs_bytes_{i}}},')
lines.append('};')
text = '\n'.join(lines) + '\n'
if not target.exists() or target.read_text() != text:
    target.write_text(text)
