#!/usr/bin/env python3
"""Emit recomp/kernel/xd3d_hash_argc.h: XD3D_COUNT name -> stdcall argument count (from each HLE's X_RET(n), or
c->r[4] += 4+4n), so the draw-stream hash (XV_DRAW_HASH) folds only real arguments, never stale stack slots.
Usage: gen_d3d_argc.py <recomp/kernel/xd3d.c> <out.h>"""
import re, sys
src = open(sys.argv[1]).read(); names = {}
for m in re.finditer(r'void xv_hle_(\w+)\(xctx \*c\)\s*\{', src):
    i = m.end(); depth = 1
    while depth and i < len(src): depth += {'{': 1, '}': -1}.get(src[i], 0); i += 1
    body = src[m.end():i]
    cnt = re.search(r'XD3D_COUNT\("([^"]+)"\)', body); ret = re.search(r'X_RET\((\d+)\)', body); add = re.search(r'c->r\[4\] \+= (\d+)', body)
    if cnt: names[cnt.group(1)] = int(ret.group(1)) if ret else ((int(add.group(1)) - 4) // 4 if add else 0)
out = ['/* generated by tools/gen_d3d_argc.py from xd3d.c: HLE name -> stdcall argument count */', '#pragma once', '#include <string.h>',
       'static inline unsigned xd3d_hash_argc(const char *name)', '{', '    static const struct { const char *n; unsigned a; } t[] = {']
out += [f'        {{ "{n}", {a} }},' for n, a in sorted(names.items())]
out += ['    };', '    for (unsigned i = 0; i < sizeof t / sizeof t[0]; ++i) if (t[i].n == name || !strcmp(t[i].n, name)) return t[i].a;', '    return 0;', '}']
open(sys.argv[2], 'w').write('\n'.join(out) + '\n'); print(f'{len(names)} HLE names, {sum(1 for a in names.values() if a == 0)} with 0 args')
