#!/usr/bin/env python3
"""Generate shaders/xv_ps_alpha_kind.h: for every xv_ps_table entry, what its fragment program's output alpha is.

  1 = texture 0's alpha, unchanged: stage 0 is a plain tex2D(tex0, ...) fetch and the final alpha is t0.a with no
      combiner stage writing t0's alpha, or r0.a (initialised to t0.a) with no stage writing r0's alpha.
  2 = the constant 1 (final alpha zero.b<unsigned_invert>).
  0 = anything else.
runtime/xv_d3d.c (XV_ALPHA_PROOF) drops the alpha test (the program's discard) for kind 1 when texture 0's upload is
proven fully opaque, and for kind 2 whenever the test accepts alpha 1. Read from the generated .cg the table points to
(its header comments list every combiner stage's alpha output). Usage: gen_ps_alpha_kind.py <stage>/shaders"""
import re, sys
from pathlib import Path
sh = Path(sys.argv[1])
table = (sh / 'xv_ps_table.h').read_text()
gxps = re.findall(r'^\s*\{ 0x[0-9A-F]{8}u, 0x[0-9A-F]{8}u, "app0:shaders/([^"]+)\.gxp"', table, re.M)
def kind(name):
    f = sh / (name + '.cg')
    if not f.exists(): return 0
    s = f.read_text()
    fin = re.search(r'^//    final alpha: (.+)$', s, re.M)
    if not fin: return 0
    fin = fin.group(1).strip()
    if fin == 'zero.b<unsigned_invert>': return 2
    stage_alpha = re.findall(r'^//    stage \d alpha: (.*)$', s, re.M)
    writes = lambda reg: any(re.search(r'(^|; )' + reg + r' = ', l) for l in stage_alpha)
    if not re.search(r'^    float4 t0 = tex2D\(tex0, IN\.texcoord0\.xy\);$', s, re.M): return 0
    if fin == 't0.a' and not writes('t0') and re.search(r'^    float  out_a   = saturate\(t0\.a\);$', s, re.M): return 1
    if fin == 'r0.a' and not writes('r0') and re.search(r'^    r0\.a = t0\.a;$', s, re.M) and \
       re.search(r'^    float  out_a   = saturate\(r0\.a\);$', s, re.M): return 1
    return 0
kinds = [kind(g.replace('.frag', '.frag')) for g in gxps]
out = ['/* generated by tools/gen_ps_alpha_kind.py from the .cg behind each xv_ps_table entry; do not edit.',
       ' * 1 = output alpha is texture 0 alpha unchanged, 2 = output alpha is 1, 0 = other. */',
       'static const unsigned char xv_ps_alpha_kind[] = {']
for i in range(0, len(kinds), 32): out.append('    ' + ','.join(str(k) for k in kinds[i:i + 32]) + ',')
out.append('};')
out.append('_Static_assert(sizeof xv_ps_alpha_kind == XV_PS_TABLE_COUNT, "xv_ps_alpha_kind out of step with xv_ps_table");')
(sh / 'xv_ps_alpha_kind.h').write_text('\n'.join(out) + '\n')
print(f'{len(kinds)} entries: kind1 {kinds.count(1)} kind2 {kinds.count(2)} other {kinds.count(0)}')
