#!/usr/bin/env python3
"""
ps_pipeline.py - collect Halo's run-time register-combiner programs from an xboxvita.log and turn
the (vertex program, combiner program) pairs the game drew with into Vita fragment shaders.

  log lines used:   [psdef] <hash> <240 hex bytes>        one per unique X_D3DPIXELSHADERDEF
                    [pspair] <vs fnv> <ps hash> ...        one per unique draw pairing
  persistent state: shaders/psdefs/<hash>.bin, shaders/psdefs/pairs.txt   (accumulated over runs)
  output:           shaders/ps_<hash>_<vsmask>.frag.cg     (compile with tools/shadercomp -> .gxp)
                    shaders/xv_ps_table.h                   runtime lookup table

Usage: tools/ps_pipeline.py <xboxvita.log> [more logs...]
"""
import glob, json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SH = os.path.join(ROOT, "shaders")
DEFS = os.path.join(SH, "psdefs")
PY = sys.executable
VAR_BITS = [("color0", 1), ("color1", 2), ("texcoord0", 4), ("texcoord1", 8), ("texcoord2", 16), ("texcoord3", 32), ("fog", 64)]
OUT_MAP = {"oD0": "color0", "oD1": "color1", "oT0": "texcoord0", "oT1": "texcoord1", "oT2": "texcoord2", "oT3": "texcoord3", "oFog": "fog"}


def vs_outputs():
    """fnv -> (gxp basename, set of varyings) from the Stage 3 vertex shader sources + xv_layouts.h."""
    lay = open(os.path.join(SH, "xv_layouts.h")).read()
    out = {}
    for m in re.finditer(r'"app0:shaders/(halo_vs_\d+)\.gxp",[^;]*?0x([0-9A-Fa-f]{8})u, \d+u\s*\n};', lay):
        name, fnv = m.group(1), int(m.group(2), 16)
        cg = open(os.path.join(SH, name + ".cg")).read()
        mo = re.search(r"outputs ((?:o\w+ ?)+)", cg)
        vary = {OUT_MAP[o] for o in mo.group(1).split() if o in OUT_MAP} if mo else set()
        out[fnv] = (name, vary)
    return out


def main():
    os.makedirs(DEFS, exist_ok=True)
    pairs_path = os.path.join(DEFS, "pairs.txt")
    pairs = set()
    if os.path.exists(pairs_path):
        pairs = {tuple(l.split()[:2]) for l in open(pairs_path) if l.strip()}
    for log in sys.argv[1:]:
        for line in open(log, "rb").read().decode("latin-1").splitlines():
            m = re.search(r"\[psdef\] ([0-9A-F]{8}) ([0-9A-F]{480})", line)
            if m:
                open(os.path.join(DEFS, m.group(1) + ".bin"), "wb").write(bytes.fromhex(m.group(2)))
            m = re.search(r"\[pspair\] ([0-9A-F]{8}) ([0-9A-F]{8})", line)
            if m and m.group(2) != "00000000":
                pairs.add((m.group(1), m.group(2)))
    open(pairs_path, "w").write("\n".join(" ".join(p) for p in sorted(pairs)) + "\n")

    vso = vs_outputs()
    table = []
    generated = set()
    for vs, ps in sorted(pairs):
        fnv = int(vs, 16)
        if fnv not in vso:
            print(f"skip pair {vs}/{ps}: no Stage 3 vertex program for fnv {vs}"); continue
        binp = os.path.join(DEFS, ps + ".bin")
        if not os.path.exists(binp):
            print(f"skip pair {vs}/{ps}: def {ps} never dumped"); continue
        name, vary = vso[fnv]
        mask = sum(b for v, b in VAR_BITS if v in vary)
        out = f"ps_{ps}_{mask:02X}"
        if out not in generated:
            generated.add(out)
            js = subprocess.run([PY, os.path.join(ROOT, "dx8_pixelshader_parse.py"), binp, "--def", "0x0", "--json"],
                                capture_output=True, text=True)
            if js.returncode != 0:
                print(f"parse failed for {ps}: {js.stderr.strip()[-300:]}"); continue
            jpath = os.path.join(DEFS, ps + ".json"); open(jpath, "w").write(js.stdout)
            r = subprocess.run([PY, os.path.join(ROOT, "pixelshader_recomp_gen.py"), jpath, "-o", SH, "--name", out,
                                "--varyings", ",".join(sorted(vary))], capture_output=True, text=True)
            print(r.stdout.strip().splitlines()[-1] if r.stdout.strip() else "", r.stderr.strip()[-300:])
            if r.returncode != 0: continue
        table.append((fnv, int(ps, 16), out, name))
    with open(os.path.join(SH, "xv_ps_table.h"), "w") as f:
        f.write("/* generated by tools/ps_pipeline.py: (vertex program fnv, combiner hash) -> fragment program */\n")
        f.write("typedef struct { uint32_t vs_fnv, ps_hash; const char *gxp; } xv_ps_entry_t;\n")
        f.write("static const xv_ps_entry_t xv_ps_table[] = {\n")
        for fnv, ps, out, name in table:
            f.write(f'    {{ 0x{fnv:08X}u, 0x{ps:08X}u, "app0:shaders/{out}.frag.gxp" }},   /* {name} */\n')
        f.write("};\n#define XV_PS_TABLE_COUNT (sizeof xv_ps_table / sizeof xv_ps_table[0])\n")
    print(f"{len(table)} pair(s), {len(generated)} fragment shader(s) -> shaders/xv_ps_table.h")


if __name__ == "__main__":
    main()
