#!/usr/bin/env python3
"""Compare a private edge/face prototype using the retained query build flags.

Compile only the separate query TU. The retained generic objects and complete
query oracle remain unchanged. Owned generated bytes stay outside the checkout.
"""
import argparse
import hashlib
import json
from pathlib import Path
import shlex
import shutil
import struct
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / 'tools'), str(ROOT)]
from tools import gen_native_query_fusion as generator
from tools import prototype_collision_edge_face as edge
from test_arm_cluster_runtime import RuntimeMachine, RAM, SIZE, STACK
from unicorn.arm_const import UC_ARM_REG_SP
from elftools.elf.elffile import ELFFile


def section(path):
    with path.open('rb') as stream:
        s = ELFFile(stream).get_section_by_name('.text')
        return s.data() if s else b''


def main():
    if not __debug__:
        raise SystemExit('Refusing optimized Python')
    p = argparse.ArgumentParser(description=__doc__)
    for name in ('xbe', 'manifest', 'retained-build', 'compile-log', 'fixture-dir', 'out'):
        p.add_argument('--' + name, type=Path, required=True)
    a = p.parse_args()
    a.out = a.out.resolve()
    if a.out.is_relative_to(ROOT):
        p.error('owned outputs must be outside source checkout')
    a.out.mkdir(parents=True, exist_ok=False)
    units = a.out / 'recomp'; units.mkdir()
    for name in ('code_013.c', 'code_016.c', 'code_028.c', 'xv_recomp_protos.h', 'xv_phase.h'):
        shutil.copy2(a.retained_build / 'recomp' / name, units / name)
    original_fused = generator.prototype.fused
    def fused(bodies, args):
        modified = dict(bodies)
        modified[0x86F50] = edge.transform(bodies[0x86F50], style)
        return '#define XV_NATIVE_COLLISION_EDGE_FACE 1\n' + original_fused(modified, args)
    for style in ('baseline', 'dynamic', 'fixed'):
        generator.prototype.fused = original_fused if style == 'baseline' else fused
        generator.generate(a.xbe, a.manifest, units, a.out / (style + '-generated.json'))
        shutil.copy2(units / 'query_fusion.c', a.out / (style + '.c'))
    generator.prototype.fused = original_fused
    # Use the actual prior production compile command. Only include roots,
    # source/output paths and non-code-changing stack reporting are replaced.
    line = next(s for s in a.compile_log.read_text().splitlines() if ' -c recomp/query_fusion.c ' in s)
    original_command = shlex.split(line)
    flags = original_command[1:original_command.index('-c')]
    flags = [arg for arg in flags if not arg.startswith('-I') and arg not in ('-MMD', '-MP')]
    flags += ['-fstack-usage', '-I' + str(units), '-I' + str(ROOT),
              '-I' + str(ROOT / 'runtime'), '-I' + str(ROOT / 'recomp'), '-I' + str(ROOT / 'recomp/kernel')]
    cc = original_command[0]
    commands = []
    rows = {}
    for lane in ('baseline', 'dynamic', 'fixed'):
        command = [cc, *flags, '-c', str(a.out / (lane + '.c')), '-o', str(a.out / (lane + '.o'))]
        subprocess.run(command, check=True); commands.append(command)
        data = section(a.out / (lane + '.o'))
        rows[lane] = dict(text_bytes=len(data), text_sha256=hashlib.sha256(data).hexdigest(),
                         stack=(a.out / (lane + '.su')).read_text())
    assert section(a.out / 'baseline.o') == section(a.retained_build / 'build/recomp/query_fusion.o'), 'production baseline .text mismatch'
    saved = json.loads((a.fixture_dir / 'commands.json').read_text())
    fixture_flags = saved[0][1:saved[0].index('-c')]
    bridge = a.out / 'bridge.c'
    bridge.write_text('#include "xv_x86rt.h"\n'
        'void nq_query_at_171f94(xctx *,unsigned);\n'
        'void f_00087EA0(xctx *);void f_00087E10(xctx *);\n'
        'void candidate_00088110(xctx *c){nq_query_at_171f94(c,0x172c95u);}\n'
        'void candidate_00087EA0(xctx *c){f_00087EA0(c);}\n'
        'void candidate_00087E10(xctx *c){f_00087E10(c);}\n')
    command = [cc, *fixture_flags, '-c', str(bridge), '-o', str(a.out / 'bridge.o')]
    subprocess.run(command, check=True); commands.append(command)
    for lane in ('reference', 'baseline', 'dynamic', 'fixed'):
        aliases = ['--defsym=original_' + addr + '=f_' + addr for addr in ('00088110','00087EA0','00087E10')]
        if lane == 'reference':
            aliases += ['--defsym=candidate_' + addr + '=f_' + addr for addr in ('00088110','00087EA0','00087E10')]
        link = saved[-1]
        ldflags = link[link.index('-nostdlib'):]
        ldflags[-1] = str(a.out / (lane + '.elf'))
        ldflags.insert(1, '-Wl,--unresolved-symbols=ignore-all,' + ','.join(aliases))
        objects = [a.retained_build / 'build/recomp' / ('code_' + n + '.o') for n in ('013','016')]
        objects += [a.fixture_dir / (str(n) + '.o') for n in range(1,7)]
        if lane != 'reference':
            objects += [a.out / (lane + '.o'), a.out / 'bridge.o']
        command = [cc, *fixture_flags, *map(str, objects), *ldflags]
        subprocess.run(command, check=True); commands.append(command)
    inputs = [a.retained_build / 'build/recomp' / n for n in ('query_fusion.o', 'code_013.o', 'code_016.o')]
    inputs += [a.fixture_dir / (str(n) + '.o') for n in range(1,7)]
    inputs += [a.compile_log, a.xbe, a.manifest]
    (a.out / 'build.json').write_text(json.dumps(dict(commands=commands, objects=rows,
        retained_baseline_text_identical=True, original_command=original_command,
        input_sha256={str(path):hashlib.sha256(path.read_bytes()).hexdigest() for path in inputs}), indent=2)+'\n')
    class Machine(RuntimeMachine):
        def step(self, uc, address, size, user):
            self.min_sp = min(self.min_sp, uc.reg_read(UC_ARM_REG_SP))
            super().step(uc, address, size, user)
        def call(self, *args, **kw):
            self.min_sp = 0xffffffff
            result = super().call(*args, **kw)
            result['peak_stack_bytes'] = STACK + 65024 - self.min_sp
            return result
    machines = {lane:Machine(a.out / (lane + '.elf'), profile=True) for lane in ('reference','baseline','dynamic','fixed')}
    for m in machines.values():
        m.imports = {k:v for k,v in m.imports.items() if v != '__wrap_xv_preempt'}
    def snapshot(m):
        result = dict(context=bytes(m.uc.mem_read(m.context,m.layout['size'])), memory=bytes(m.uc.mem_read(RAM,SIZE)))
        for name, size in [('ct_yields',4),('ct_events',4),('ct_seen',4),('ct_boundary',4),('ct_original_pages',4096),('ct_alternate_pages',4096)]:
            result[name] = bytes(m.uc.mem_read(m.symbols[name],size))
        root = struct.unpack('<I',m.uc.mem_read(m.symbols['g_xpt'],4))[0]
        result['root'] = 'original' if root == m.symbols['ct_original_pages'] else 'alternate' if root == m.symbols['ct_alternate_pages'] else root
        return result
    results = []
    for depth in (1,16):
        for variant in (0,3,4,8,12,15,1<<25):
            lanes = {}; expected = None
            for lane,m in machines.items():
                m.call('arm_prepare',(depth,variant,100000))
                stats=m.call('arm_original' if lane=='reference' else 'arm_candidate',fpscr=0)
                actual=snapshot(m)
                if expected is None:
                    expected=actual; expected_fp=stats['fpscr']
                checks={key:actual[key]==value for key,value in expected.items()}
                checks['fpscr']=stats['fpscr']==expected_fp
                lanes[lane]=dict(stats=stats,checks=checks)
                assert all(checks.values()), (depth,variant,lane,checks)
            results.append(dict(depth=depth,variant=variant,budget=100000,fpscr=0,lanes=lanes))
            (a.out/'result.json').write_text(json.dumps(results,indent=2)+'\n')
            print('PASS retained query',depth,variant,{lane:(r['stats']['instructions'],r['stats']['peak_stack_bytes']) for lane,r in lanes.items()},flush=True)


if __name__ == '__main__':
    main()
